In [1]:
import os

In [2]:
os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_API_KEY_HERE"

In [3]:
from langchain.vectorstores import Chroma
#from langchain_openai import OpenAIEmbeddings
#from langchain_openai import OpenAI

In [4]:
from langchain.document_loaders import DirectoryLoader
from langchain.document_loaders import TextLoader
from langchain_community.document_loaders import PyPDFLoader

In [10]:
os.listdir("amu data")

['terms (1).pdf',
 'phdregulation.pdf',
 'schooladmguide_fn.pdf',
 'HOSPITAL.pdf',
 'PROCEDURE FOR NON-TEST COURSES (1).pdf',
 'PROCEDURE FOR NON-TEST COURSES.pdf',
 '.DS_Store',
 'ordinance_phd.pdf',
 'terms.pdf',
 'UFM_RULES-F2 (1).pdf',
 'fn_supplement.pdf',
 'guide to admission.pdf',
 'PROCEDURE FOR DEPARTMENTAL TEST COURSES.pdf',
 'termsand privacy policy.pdf',
 'PROCEDURE FOR DEPARTMENTAL TEST COURSES (1).pdf',
 'UFM_RULES-F2.pdf',
 'LIST OF RECOGNIZED BOARDS OF EXAMINATION AND UNIVERSITIES.pdf',
 'amu counselling guide (1).pdf',
 'medicineguide.pdf',
 'schooladmguide.pdf',
 '6c79f5140da71180f8e833763617f2b4.pdf',
 'e07cedbf89d39c7931a327df851484db.pdf',
 'unaniguide.pdf',
 'Examination (Control of Unfair Means and Disorderly Conduct) Regulations-2019.pdf',
 'amu counselling guide.pdf']

In [1]:
for t in os.listdir("amu data"):
    if t==".DS_Store":
        continue
    pdf_file=t
    for page_number in range(len(pdf_file)):
            page = pdf_file[page_number]
            
            # Get the text on page
            text = page.get_text().strip()
            text_data.append({"response": text, "name": page_number+1})
            # Get the list of images on the page
            images = page.get_images(full=True)
    
            # Loop through all images found on the page
            for image_index, img in enumerate(images, start=0):
                xref = img[0]  # Get the XREF of the image
                base_image = pdf_file.extract_image(xref)  # Extract the image
                image_bytes = base_image["image"]  # Get the image bytes
                image_ext = base_image["ext"]  # Get the image extension
                
                # Load the image using PIL and save it
                image = Image.open(io.BytesIO(image_bytes))
                image.save(f"extracted_images/image_{page_number+1}_{image_index+1}.{image_ext}")

NameError: name 'os' is not defined

In [6]:
texts=[]
for t in os.listdir("amu data"):
    if t==".DS_Store":
        continue
    print(t)
    path=f"amu data/{t}"
    loader=PyPDFLoader(path)
    text=loader.load()
    texts+=text

terms (1).pdf
phdregulation.pdf
schooladmguide_fn.pdf
HOSPITAL.pdf
PROCEDURE FOR NON-TEST COURSES (1).pdf
PROCEDURE FOR NON-TEST COURSES.pdf
ordinance_phd.pdf
terms.pdf
UFM_RULES-F2 (1).pdf
fn_supplement.pdf
guide to admission.pdf
PROCEDURE FOR DEPARTMENTAL TEST COURSES.pdf
termsand privacy policy.pdf
PROCEDURE FOR DEPARTMENTAL TEST COURSES (1).pdf
UFM_RULES-F2.pdf
LIST OF RECOGNIZED BOARDS OF EXAMINATION AND UNIVERSITIES.pdf
amu counselling guide (1).pdf
medicineguide.pdf
schooladmguide.pdf
6c79f5140da71180f8e833763617f2b4.pdf
e07cedbf89d39c7931a327df851484db.pdf
unaniguide.pdf
Examination (Control of Unfair Means and Disorderly Conduct) Regulations-2019.pdf
amu counselling guide.pdf

In [7]:
len(texts)

386

In [8]:
# loader=PyPDFLoader('amu data/schooladmguide_fn.pdf')
# text=loader.load()

In [9]:
len(text)

16

In [10]:
type(text)

list

In [11]:
# loader=DirectoryLoader("",glob="ipctextcorpus.txt",loader_cls=TextLoader)

In [12]:
# document=loader.load()

In [13]:
# len(document)

In [14]:
# document=document+text

In [15]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [16]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=200)

In [17]:
text=text_splitter.split_documents(text)

In [18]:
print(texts)

[Document(metadata={'source': 'amu data/terms (1).pdf', 'page': 0}, page_content='Online Payments Terms & Conditions  \n \nThis online payment system is provided by Aligarh M uslim University Aligarh (AMU). The \nAMU may update these terms from time to time withou t any prior notice or reason and \nany changes will be effective immediately on being set out here. Please ensure you are \naware of the current terms. The country of domicile  for AMU is India. \nTerms & Conditions \nPlease read these terms carefully before using the online payment facility. Using the \nonline payment facility on this website indicates t hat you accept these terms. If you do \nnot accept these terms do not use this facility. AM U reserves the right to change the fees \nat any time. \nYour payment will normally reach AMU account to whi ch you are making a payment \nwithin two working days. \nWe cannot accept liability for a payment not reachi ng the correct AMU account if \npayment is refused or declined by the credit/debit card supplier for any reason. \nIf the card supplier declines payment, AMU is under  no obligation to bring this fact to \nyour attention. You should check with your bank/cre dit/debit card supplier that payment \nhas been deducted from your account. \nIn no event will AMU be liable for any damages what soever arising out of the use, \ninability to use, or the results of use of this sit e, any websites linked to this site, or the \nmaterials or information contained at any or all su ch sites, whether based on warranty, \ncontract, tort or any other legal theory and whethe r or not advised of the possibility of \nsuch damages. \nRefunds, if applicable, at the discretion of the ad ministration of the AMU, will only be \nmade to the debit/credit card used for the original  transaction. For the avoidance of \ndoubt nothing in this Policy shall require AMU to r efund the Fees (or part thereof) unless \nsuch Fees (or part thereof) have previously been pa id. \nSecurity \nAll payment details which are entered through this payment gateway are encrypted \nwhen the Student, or third party making payment, en ters them. Communications to and \nfrom the Service Provider’s site are encrypted. \nAMU shall not be liable for any failure by the Stud ent or third party making payment of \nFees to properly protect data from being seen on th eir screen by other persons or \notherwise obtained by such persons, during the onli ne payment process or in respect of \nany omission to provide accurate information in the  course of the online payment \nprocess. \nService Provider \nOnline Payments of Fees can be made by Credit / Deb it card or Net banking. These \npayments are not collected by AMU directly but thro ugh the Service Provider. \nPrivacy Policy \nThis Privacy Policy applies to all of the products,  services and websites offered by AMU. \nAMU may post product specific privacy notices or He lp Centre materials to explain our \nproducts in more detail without any prior notice. \nWebsite Detail: \nEntire content of the website has been gathered to the best of our knowledge and belief, \nand the university endeavors to keep it up to date.  In particular, we reserve the entire \nright to update and/or modify and/or remove this da ta anytime and without any prior \nnotice. Please note that AMU holds no responsibilit y for incorrect or no longer correct \nstatements, quotes or descriptions and thereby excl udes liability for any losses resulting \nfrom such wrong information. '), Document(metadata={'source': 'amu data/terms (1).pdf', 'page': 1}, page_content='Further, AMU has every right to bring about legal a ction on students who \nmisuse/alter/reproduce the content/ information ava ilable on the website \nData Privacy Policy \nOur data privacy policy strictly conforms as per th e regulations set down in accordance \nto the protection of data collected from people vis iting our website. AMU treats all \npersonal data obtained via internet and our website  carefully and confidentially so that \nno physical/mental harm is instilled up on the pers on, with regard to the collected data. \nPersonal data that has possibly been known to us wi ll be kept secret, privacy will be \nrespected and information will be used exclusively for the purpose for which it was made \nknown to us. \nChanges to our Privacy Policy \nAMU reserves the entire right to modify/amend/remov e this privacy statement anytime \nand without any prior notice or reason. Nothing con tained herein creates or is intended \nto create a contract/agreement between AMU and any user visiting the AMU website or \nproviding identifying information of any kind. \nArbitration and Jurisdiction \nIn the event of any dispute, the High Court, Allaha bad shall have exclusive jurisdiction \nsubject to condition that the either party shall be  entitled to refer such dispute to the sole \narbitration of the Vice-Chancellor, Aligarh Muslim University, Aligarh or his nominee who \nshall decide the dispute according to Arbitration A ct and whose decision shall be final \nand binding on the parties. In case, the nominee of  the Vice-Chancellor, Aligarh Muslim \nUniversity, Aligarh fails to act as arbitrator, the  Vice-Chancellor may change the \narbitrator, the person so nominated by the Vice-Cha ncellor will proceed further in the \narbitration from the stage the previous nominee lef t the arbitration. '), Document(metadata={'source': 'amu data/phdregulation.pdf', 'page': 0}, page_content='1 \n REGULATIONS FOR Ph.D.  \nChapter XXV ( E) of the Ordinances (Academic)  \n \n1. Vacancy notification  \n \nThe University  shall notify the maximum number of admissions to be made in each \ndiscipline  in the ensuing academic session after leaving one-third of the total available \nseats vacant and taking i nto consideration: \n \na) The number of faculty members available in each discipline  for supervision.  \nb) The number of admissions in Ph.D. that can be made according to the prescribed  \nrules for supervision. \nc) The Library and Laboratory facilities and other essential resources available, to the \nextent this information is relevant for fixing  the nu mber of candidates who can be \nadmitted. \n \n2. Supervision  \n \n(i) Any permanent faculty member working as Professor/Associate Professor in the \nUniversity with a Ph.D., and at least five research publications in peer -reviewed or \nrefereed journals and any permanent faculty member working as Assistant Professor \nwith a Ph.D., and at least  three research publications in peer -reviewed or refereed \njournals may be recognized as a Research Supervisor  \n \nProvided that in areas/disciplines where there are no or only a limited nu mber of peer -\nreviewed or refereed journals,  the Board of Studies ( BoS)  may relax the above \ncondition for the recognition of a person as Rese arch Supervisor with reasons to be \nrecorded in writing. \n \n \n(ii) The allocation of Research Super visor for a selected research sch olar shall be   \nrecommended  by the BoS concerned depen ding on the number of sch olars per \nResearch Super visor, the available specialization of the Super visors and research \ninterests of the scholars. \n \n(iii) At any given point of time a Research Super visor who is  a Professor can guide up to \na maximum  of Eight (8) research scholars ; an Associate Professor can guide up to a \nmaximum  of Six (6) research scholars  and an Assistant Professor can guide up to a \nmaximum of Four (4) research scholars . This includes regular scholars and Persons \nwith Disability ( PwD) category scholars . \nProvided that a teacher of the University, at any point of time, can guide a maximum \nof two Foreign nationals and two part -time scholars only over and above her/his norm \nof guiding scholars given above.   \nAt any point, the total number of Ph.D. scholars und er a teacher , either as a supervisor \nor a co-supervisor, shall not exceed the number as prescribed  above.  \n \n(iv) Teachers of the University who have less than three years to retire shall not be \nrecommended for the appointment as supervisor by the BoS.  However, such teachers \ncan continue to supervise Ph.D. scholars who are already  registered until \nsuperannuation and as a co -supervisor after superannuation, but not after attaining the \nage of 70 years.  '), Document(metadata={'source': 'amu data/phdregulation.pdf', 'page': 1}, page_content='2 \n  \n(v) In case of relocation of woman research scholar of the University due to marriage, the \nresearch data shall be allowed to be transferred to the University to which the scholar \nintends to relocate provided all the other conditions in these Regulations are followed \nin letter and spirit  and the research work does  not pertain to the project secured by \nthe University / Supervisor from any funding agency. The research scholar will, \nhowever, give due credit to the parent guide and the University  for the part of research \nalready done. \n \n2.1 Co-Supervision  \n(i) Co- Supe rvisor(s), if required, can be appointed  in inter-disciplinary areas preferably \nfrom other Departments of Studies or from other related institutions from outside the \nUniversity having comparable or higher NIRF/Times Higher Education/QS Ranking  \nwith the approval of the CASR.  \n \n(ii) Co-supervision of theses is justified in the following situations:  \na) The thesis is interdisciplinary or inter -sectoral, as it requires the respective \ncontribution of the two supervisors in different fields of knowledge. The RAC \nmust justify the contribution of both the initial supervisor and the proposed \nco-supervisor.  \nb) The thesis is under international or inter -institutional joint supervision, in that \nthe proposed co -supervisor belongs to a different institution, whether national \nor foreign, public or private.  \nc) The thesis aims to be awarded in collaboration with industry.  \n \n(iii)The teachers of the university may be permitted to guide Ph.D. scholars admitted to \nother universities of comparable or higher NIRF/Times Higher Education/QS \nRanking as a co -supervisor, provided that  \n \na) There is a vacancy with the teacher the candidate intends to work under.  \nb) The sponsoring university seeks prior permission in the matter and  \nc) The concerned BoS approves it.  \n \n3. Application for Admission  \n \n(i) Candidates can apply for admission to Full -time/Part -time Ph.D. programme in \nthe Faculties of Agricultural Sciences, Arts, Commerce, International Studies, \nLife Sciences, Science, Social Sciences, Theology, Engineering & Technology, \nLaw, Management Studies & Research, Medicine and  Unani Medicine.  \n \n(ii) Candidate eligible for admission to the Ph.D. programme  in more than one \nFaculty of the University can apply for the same but such a candidate will have \nto fill separ ate Application Form for each Faculty. However, s/he can apply only \nin a maximum of two  disciplines within the same Faculty. \n \n(iii) All candidates shall submit the duly filled Application Form on the online \nportal  of the CoE  on or before the last date announced by the University.  \n \n(iv) Exemption from appearing in the written test as per the clause 3.1(ii) -(iii) of \nChapter XXV (E) of the Ordinances (Academic) will be applicable to only those '), Document(metadata={'source': 'amu data/phdregulation.pdf', 'page': 2}, page_content='3 \n candidates who are eligible for the same on the notified last date of submitting  of \nApplication Form and have submitted  documentary proof of the same  with their \nApplication Form.  \n \n4. Conduct of Admi ssion Test  \n \n(i) Written  Test: An eligible candidate, as per proviso 2.1 of Chapter XXV (E) of the \nOrdinances (Academic), shall be requi red to appear in the written test, except \n(a)foreign nationals and (b) those who are exempted  as per proviso 3.1(ii) . \n \n(ii) The test pape r, carrying 80 marks shall be of ninety minutes’ duration. It shall \nconsist of the following sections :  \n \nSection A:  Research Aptitude / Methodology  \nIt shall be of 45 minutes’ duration.  There shall be 40 Multiple Choice Questions \n(MCQs) of 1 mark each on Research Aptitude / Methodology. \n \nSection  B: Subject Specific  \nIt shall be of 45 minutes’ duration.  There shall be 40 Multiple Choice Questions \n(MCQs) of 1 mark each covering equitably, as far as possible, all topics of the \nsyllabus.  \n \n(iii) There shall be no negative marking.  \n \n(iv) The CoE  would request the Deans of Faculties to provide the names of the \nteachers who will be contributing questions (MCQs) to create a question pool \nfrom which the paper for Section -A shall be set and moderated.  \n \n(v) The CoE  would request the Chairman of the Department concerned to provide the \nnames of the teachers who will be contributing questions (MCQs) to create a \nquestion pool from which the paper for Section -B shall be set and moderated.  \n \n(vi) Paper for both Section -A and Se ction -B will be set in the CoE office The Dean \nof the Faculty shall be responsible for coordinating preparation of three sets of \npapers of Section A, while the Chairman of the Department concerned shall be \nresponsible for coordinating the preparation of th ree set s of papers of Section B \nas per procedure approved by the Vice -Chancellor from time to time.  \n \n(vii) The CoE shall present the above sets of papers before the Vice -Chancellor , who \nwill approve one set of paper of Section -A for each Faculty and one set of p aper \nof Se ction -B for each discipline . \n \n(viii) CoE shall be responsible for  \n \n(a) the printing of Question Booklets.  \n(b)  the conduct of the written test  \n(c)  uploading the Answer Key, and  \n(d) resolving all challenges to the Answer Key.  \n '), Document(metadata={'source': 'amu data/phdregulation.pdf', 'page': 3}, page_content='4 \n (ix) Evaluation of the MCQs shall be done in the CoE office.  \n \n(x) Candidates should  secure 50% or more marks in the Written Test to  be eligible  for \nPresentation -cum-Interview . However, a relaxation of 5% marks shall be allowed \nfor PwD  candidates, and they should secure a minimum of 45% marks in the \nWritten Test to be eligible for Presentation -cum-Interview.  \n \n(xi) Presentation -cum-Interview:  All candidates who qualify the written test and those \nwho were exempted as per  Clause 3.1(ii) of Chapter XXV(E) of the  Ordinances \n(Academic) shall be called for Presentation -cum-Interview.   \n \nIn addition, Fo reign national candidates shall  also be required to appear for \nPresen tation-cum-Interview as per Clause 3.1(iii) of Chapter XXV(E) of the \nOrdinances (Academic).  \n \n(xii) Prese ntation-cum-Interview shall be of 20 marks and will normally be held \nwithin 1-2 weeks following the declaration of the list of candidates short -listed as \nper Clause 4(x) & (xi) of these Regulations. \n \n(xiii) Each short -listed candidate will give a prese ntation, not exceeding 15 minutes, \nrelated to his proposed area of research, and appear for an interview before the \nPresentation -cum-Interview Committee.   \n \n(xiv) The prese ntation shall be in the English language, ex cept for those appearing in \nthe Departments of Arabic, Hindi, Modern Indian Lan guages, Persi an, Sanskrit, \nUrdu, and Theology, in which the prese ntation shall be  made in the respe ctive \nlanguage or language approved by the concerned  CASR on the re commendation of \nBoS. \n \n(xv) The Prese ntation-cum-Interview Committee in each department shall consist of \nthe Chairman , two available senior most faculty members of the department and a \nnominee of the Vice -Chancellor.  \n \n(xvi) The Presentation -cum-Interview shall be open to all teachers of the Department . \nHowever,  questions shall only be asked by the Presentation -cum-Interview \nCommitt ee. \n \n(xvii)  A candidate who fails to appear for Presentation –cum-Interview shall not be \neligible for admission.  \n \n(xviii)  The Chairman of the Department concerned  shall  send the marks obtained by \nthe candidates in the Presentation -cum-Interview  in a sealed cover to the CoE to \ndetermine the overall merit list for each discipline.  \n \n5. Offer of Admission  \n \n(i) A single merit list of candidates who appeared in the Presentation -cum-Interview \nof each discipline shall be drawn by the CoE office based on aggregate of m arks \nin written test and Presentation –cum-Interview with the following break -up: '), Document(metadata={'source': 'amu data/phdregulation.pdf', 'page': 4}, page_content='5 \n a) Written Test: 80 Marks  \nb) Presentation -cum-Interview: 20 Marks.  \n \nHowever, for candidates exempted from the Written Test as per the clause 3.1(ii)  of \nChapter XXV( E) of the Ordinances (Academic) , the weightage of Presentation -cum- \ninterview shall be considered out of  100 marks . \n \n(ii) Based on the combined merit list, candidates shall be selected for admission equal \nto number of vacancies notified in the discipline concerned, strictly on merit as per \nadmission policy of the University and notified after approval of the Vice -\nChancellor.  \n \nFurthe r, foreign nationals shall be considered for admission over and above the \nnotified seats, only  on the basis of their merit in the qualifying examination and \nPresentation –cum-Interview,  subje ct to the approval by the BoS of the synopsis of \nthe proposed research work specified  by them in their Application Form.   \n \n(iii) Provisional admission  shall  be offered  to the selected candidates and they  shall \nbe asked to complete their provisional admission  as per notified schedule and \nprocedure.  \n \n(iv) However, foreign nationals shall be allowed to block their seat as per notified \nprocedure of the University and subsequently complete the admission  within a \nperiod of six months from the date of the offer made to them, subject to the \ncandidate acquiring a research visa to pursue the Ph.D. programme.  \n \n(v) A candidate selected for admission to a part -time Ph.D. programme shall submit a \n“No Objection Certificate” from the Office of the Registrar , at the time of \nadmission clearly stating therein that:  \na) The candidate is permitted to pursue studies on a part -time basis.  \nb) His/her official duties permit him/her to devote sufficient time to research.  \n \n6.    Course Work  \n \n(i) Each provisionally admitted candidate , will have to undertake the prescribed  \ncourses  as per Clause 4 of Chapter XXV(E) of the Ordinances (Academic). \n \n(ii) Each course will have a maximum of 100 marks. The courses  will have the \nfollowing components of evaluation: \n \nSessi onal  : 30 marks \n             Examination  : 70 marks \n \n(iii) The ex amination in the courses  prescribed sh all be of two hours’ duration each.  \n \n(iv) A Ph.D. scholar has to obtain a minimum of 55% of marks in each of the \nprescribed courses in order to be eligible to continue in the pr ogramme and \nsubmit the thesis.  \n '), Document(metadata={'source': 'amu data/phdregulation.pdf', 'page': 5}, page_content='6 \n (v) The combined marks obtained by a Ph.D. scholar in various components of \nevaluation of a course shall be converted into regular letter grades with their \nequivalent grade points as specified below:  \n \nMarks \nRange \n(Out of \n100) Grade Grade \nPoints Description \n90-100 O 10 Outstanding \n80-89 A+ 9 Excellent \n70-79 A 8 Very good \n60-69 B+ 7 Good \n55-59 B 6 Above Average \n0-54 F 0 Fail \n I 0 Incomplete \n Y 0 Detained  \n Z 0 Withheld  \n \n7.     Attendance and Leave  \n \n(i) A research scholar  is required  to sign on all working  days of the Faculty in an \nattendance register to be kept in the office of the concerned  Department, except when \ns/he is on duty/sanctioned leave. \n \n(ii) A research scholar  shall be eligible to avail a leave of 30 days in an academic year.  \nS/he s

In [30]:
type(texts)

list

In [20]:
text[:200]

[Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 0}, page_content='1 \n \n \n USER  MANUAL FOR ONLINE REGISTRATION, CHOICE FILLING \nAND AD MISSION \n(Session 202 4-25) \n \n• Admissions to the Aligarh  Muslim  University are be ing effected through the Online Counselling \n/Admission portal for admissions (https://couns elling.amuonline.ac.in). \n• All the eligible candidates who figure in the Select/Chance Memo/Nomination Lists are required to \nregister online as per notified schedule  of the concerned course on the Online portal for Counselling and \nAdmission from places of their convenience preferably using a Laptop/Desktop. \n• Candidates who do not complete all the steps leading to completion of admission as detailed below \nfor the course conc erned  as per notified schedule will be treated as candidates who are not interested \nin taking admission in the conc erned  course of study. HENCE , they will not be considered for \ncouns elling/admission to the con cerned  cour se and their allotted seat, if any, will be CANCELLED . \nI.      Registration'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 0}, page_content='couns elling/admission to the con cerned  cour se and their allotted seat, if any, will be CANCELLED . \nI.      Registration \nII.      Login \nIII.      (A) Document Upload (Scanned /Photo, both sides) \n(B) Exercising of Choices and its locking (wherever required) \n(C) Submission of Choices and the U ploaded do cuments. \nIV.      Re-submission of documents (if required) as per verifier(s) report. \nV.      Payment of requisite Ad mission Fee,  if offered ad mission. \nDetailed proced ure for the same is described below: \nI.  REG ISTRAT ION \n1. All short-listed candidates (i.e. who figure in the Select/Chance  Memo/Nomination Lists of the concerned \ncourse) are required to visit the AMU Online portal for Counselling and  Admission and click on \n“Register” button (marked in Red box).'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 1}, page_content='2 \n \n \n \n 2. The candidate is required to enter the Roll Number, Application Number & Date of Birth exactly the \nsame as p er his/her Application Form/Admit Card details of the course concerned. \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n3.  The candidate has to sign on the declaration containing that he/she has read the counselling procedure .  \n \n \n \n \n4 .  The candidate is also required to enter his/her valid email and  10 digits’ mobile number.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 2}, page_content='3 \n \n \n Upon  pressing the “Click to verify” button, it will prompt  for the OTP sent on the provid ed email. \nFill up the OTP received on the provid ed email. This will validate the email account of the \ncandidat e. \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \nIn a similar fashion,  the candidate  will also be required to enter his/her mobile number  and \nvalidate the  same by submitting the OTP received on the Mobile Numb er. \n  \n5. The candidate is required to enter a Password of his/her choice, as per the password policy shown during \nthe Registration process and reconfirm it. \n \n \n \n6.    The candidate is then required to check the CAPTCHA and press “Register” button to complete the \nRegistration process.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 3}, page_content='4 \n Note: \n(a)   Candid ate should remember his/her password for continuation of the remaining process of login, \ndocument upload, ch oice filling (wherever required) and i ts submission and c ompletion of a dmission, \nif offered. This password or  changed  password (if any carried out by the cand idate) must be remembered \ntill the completion of admission process. The University will not be responsible for any cons equences \narising out of forgotten password/misuse of password. \n(b)   Candid ate whose name does not figure  in the Select/Chance Memo/Nomination Lists of the concerned \ncour se is not permitted to Register for the course concerned.  \n(c)   Candid ate whose  name figures in the Select/Chance Memo/Nomination Lists of more than one course \nof study need not Register separately for each course  of study. S uch can didates should Lo gin through \ntheir already Registered accou nt for all cour ses of study where they have  been  short-listed for \ncouns elling/admission.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 4}, page_content='5 \n \n \n II.      LOGIN \n \n7.    After registration and subseque nt verification of email and mobile number submitted by the candidate, \nthe candidate can “Login” using his/her email and password.  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n8.    In case, a candidate has forgotten his/her password,  he /she can  reset the same by clicking on the “Forgot \nPassword” link. \n \n \n \n9. The candidate would be required to enter his/her email, and an OTP/Password  Reset link would be sent \nto his/her registered email.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 5}, page_content='6 \n (A)  UPLOADING  OF DOCUMENTS \n \n9.    After successful login, the screen “Uploads” for uploading of docu ments is visible before the candidate. \nThe candidate has to select the course from the drop down for which he/she is uploading the documents. \nDocuments are to be uploaded separately for each course  within the stipulated duration as mentioned in \nthe counselling schedule.  \n \n \n \n \n10. Candidate is MANDAT ORILY required to Upload the following colour scanned  copies (both sides, \nif back side is not blan k) of his/her documents as given below. \na.   Class X/High Scho ol Certificate in support of date of birth. \nb.   Mark sheet of all examinations passed up to the Qualifying Examination for the concerned course \nof study. \nc. Mark sheet(s) (all semesters/parts/transcript) of Qualifying Examination for the concerned course \nof study. \nd.   Spec ial Category Certificates, if applicable. \nExplana tion:'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 5}, page_content='of study. \nc. Mark sheet(s) (all semesters/parts/transcript) of Qualifying Examination for the concerned course \nof study. \nd.   Spec ial Category Certificates, if applicable. \nExplana tion: \n• A candidate short-listed for a Post-Graduate (PG) level course like MBA  will be required to sub mit \nall mark sheets up to Graduation (i.e. X, XII or equivalent & Graduation). Similarly, a cand idate short-\nlisted for a Under-Gradua te (UG) level course like B.A. will be required to submit all mark sheets up to \nClass XII (i.e. X  & XII). \n• A Candidate who has been short-listed for coun selling/admission to a course of study under Spec ial \nCategory as claimed by him/her will have to upload relevant documents justifying his claim in the \nconcerned category, failing which he/she will not be considered for admission under the S pecial \nCategory concerned.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 6}, page_content='7 \n \n \n \n \n 11. Candidate may also Upload the following colour scanned copies (both  sides) of his/her documents \nas given be low. \na.   Migration Certificate \nb.   Mark sheets of other examinations passed, if any. \nc.   No-objection Certificate/Leave Sanc tion Order, if applicable. \nd.   Any other relevant Document (e.g. GATE Certificate for admission to M.Tech. Programme) \ne. The permissible file format for uploading photo and signature are: jpg, jpeg, bmp, etc., while \npermissible format for uploading docu ments are: pdf, jpg, jpeg etc. \n \n12.  To upload a document, the procedure is as follows: \n \nStep 1: Upon clicking on “select” field, a dropdo wn will appear, select the relevant nomenclature of the \ndocu ment you may wish to upload'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 7}, page_content='8 \n \n \n Step 2: Specify the name of the document to be uploaded (e.g. Marksheet-Ist Semester). \n \n \n \nStep 3: Click on the “choose file” button and browse the location where the file to be up loaded is saved. \n \n \n \n \n \n \n \n \n \n \nStep 4: Upon browsing the file location, click on the “upload” icon to upload the desired document. \n \n \n \nStep 5: One may use the “Reset” Button if the candidate desires to cancel the upload of any docu ment, if in \ncase any wrong “upload type” or file is selected.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 8}, page_content='9 \n \n \n \n \n Step 6: Once a document is uploaded, the counter will dep ict the number of documents uploaded under each \nsection. \n \n \n \n \n \n \n \n \n \n \nStep 7: For confirmation, the candidate may click on  the relevant field under uploaded  documents to verify \nwhether the document is up loaded correctly or not. One may a lso use the “Bin” icon to delete any \ndocu ment/photograph/signature, if uploaded incorrectly. \n \n \n \nStep 8: Repeat the above steps to upload all the relevant documents. \n \n \nNote: In document uploads, multiple documents under single field may be uploaded.  However, in case of \nphoto graph and  signature only one each  is allowed. \n(e.g. mark sheets of all semesters/year of gradua tion may be uploaded one after the other under Graduation tab \nand may be na med as MS1, MS2, M S3, MS4  etc.) \n \n \n13.  Once the candidate has uploaded  all the relevant documents required, he/she may click on the “Next” \nButton to proceed further.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 9}, page_content='10 \n \n \n 14.  After navigating to the next screen, i.e. the “Counselling Dashboa rd”, the candidate would be shown \nhis/her credentials (details of the course in which his/her name is there in select/chance memo/nomination \nlist) as available in the database of the Uni versity. \n \n \n15. Use “Proceed” button against the course for which the candidate desires to complete \ncoun selling/Admission formalities. Here the initial status shows that submission is still pending. \n16.  Once the proceed b utton is clicked the pop-up dialogue box may show  “Your name also appe ars in \nnomination list in special category. Click OK to proceed in special category or CANCE L to continue \nin gen eral category”, \n17.  If the can didate wishes to proceed in the general list he/she may click the cancel button to continue. \n \n \n \n \n \n \n \n \n \n \n \n \n \n18.  However, if the candidate desires to opt for nomination in any special category, he/she may click on “OK”'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 9}, page_content='18.  However, if the candidate desires to opt for nomination in any special category, he/she may click on “OK” \nbutton. This will again navigate the candidate to document upload page, where he/she is required to upload \nthe docu ment in support of the sp ecial category claimed.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 10}, page_content='11 \n \n \n (B)  FILLING  & GIVING PREFERENC E FOR  CHOICES (W HEREVE R APPLICABLE) \n \n19.  For filling of choices, the candidate is required to press the “Proceed” button \n \n20.  The available course specific choices (wherever applicable) based on the candidate’s application will also be  \ndisplayed. Candidate will be required to indicate his/her order  of preference for the choices from a mongst \nthose listed under the concerned course of study. The candidate can modify/chan ge the order of preference as \nmany times as required during the Ch oice Filling pe riod. \n \nThe “proceed” icon against a course is active only as per the schedule of the counselling dates. \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n21.  The preference order of choices may be done  by selecting a particular choice from the Offered Choice List \n(available Choices) and pressing the “Add” button so that it gets added to the Confirmed List. The cand idate'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 10}, page_content='(available Choices) and pressing the “Add” button so that it gets added to the Confirmed List. The cand idate \nmay remove any cho ice from the Confirmed List in a similar way by s electing that choice and p ressing the \n“Remove” button. \n \n \n    \n \n22. The candidate should select and add only those choices in which he/she is interested from the available \nchoices applicable for the conce rned course in “Order of Preference”. First being the most preferred \nchoice and last being the least preferred choice.  \n \n \n23. the c andidate has to also give an unde rtaking that the documents uploaded  by him/her are genuine and if at \nany stage any document is found to be forged/tampered, the admission of the candidate will be canc elled'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 11}, page_content='12 \n \n \n and it will be the sole responsibility of the candidate. Further, the University will be free to take any  legal \naction against him/her as per law. \n \n \n \n \n(C)  SUBMISSION \n \n25.  The candidate is required to finally click on  the submit button for final submission of docu ments and cho ices \nfor subsequent verification. Once submission is done successfully the status against the course concer ned \non the Counselling Dashboard  will change from “Submission Pending ” to “Submitted”. \n \n \n \n \n \n \n \n \n \n \n \n \n26.  The candidate may modify the submitted choices within the time duration given for uploading of docu ments \nand filling of  choices in the counselling schedule by pressing the “Modify” button and repeating the whole \nprocess of submission. Every time the candidate opts for modification, its manda tory to click the submit button \nelse the last submitted order of preference will be retained.'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 11}, page_content='process of submission. Every time the candidate opts for modification, its manda tory to click the submit button \nelse the last submitted order of preference will be retained. \n27.  A cand idate who does not submit the choices/undertaking as  per notified schedule will be treated as cand idate \nwho is not interested in taking ad mission in the concerned course of study and will therefore not  be considered \nfor counselling/admission to the concerned co urse of study. \n28.  If a cand idate logs in after expiry of the time for choice filling, then the choices cannot be submitted , and if \nalready  submitted, then the same cann ot be modified or altered. \n \nVER IFICATION OF DOCU MENTS \n \n29.  The uploaded Documents will be verified ONLINE by the Verifying Officers. \n30.  During on line verification, the Verifying Officer may either find the candidate eligible for provisional \nadmission based on the provisional docu ments submitted by  the candidate or alternatively find the cand idate'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 11}, page_content='admission based on the provisional docu ments submitted by  the candidate or alternatively find the cand idate \nineligible on account of not fulfilling the eligibility criteria of the course concerned as per uploaded \ndocuments or due to non-uploading of the relevant docu ments by the candidate,'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 12}, page_content='13 \n 31.  The status of the candidate with regard to the verification of docu ments will be visible to the candidate in their \nlogin account on the Couns elling-cum-Admission portal. \n32.  Candidates whose docu ments are not accepted by the Verifying Officer will not be considered for \ncoun selling/admission to the con cerned co urse of study. \n \nIV.    RE-SUBMISSS ION WINDOW (AS PER VER IFIER(S) REPOR T) \n \n33.  The candidates will be given a resubmission  window  as per  notified schedule if the verification report is \nadverse. During this period the candidate has to upload and sub mit the rejected documents again as p er the \nobjections raised by the verifier. Resubmission is to be only against the documents which shows \n“Resubmission Required ”. \n \n \n \n \n34.  The re-submitted docu ments will be scrutinized  again  by the verifier  and admission  coordinator . \nCandidates wh ose docu ments are not accepted by the Verifying Officer /Admission Coordinator will not be'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 12}, page_content='Candidates wh ose docu ments are not accepted by the Verifying Officer /Admission Coordinator will not be \nconsidered for counselling/admission to the concerned co urse of study and no  further correspon dence in this \nmatter will be considered. \n \nV.   OFFER OF ADMISSION & PAYMENT OF FEE \n \n35.  Based on candidate’s rank, his/her category and filled choices, he/she may be provisionally allotted a seat in \nthe concerned course after online verification of his/her documents. \n36.  A cand idate who has been allotted a seat, and wishes to complete the admission formalities, is required to \nLog-in to his/her account on coun selling-cum-admission portal to accept the allotted seat and SECUR E \nthe provisional admission in the concerned co urse of study by  depo siting the ADMISSION FEE .'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 13}, page_content='14 \n  \n \n \n \n \n \nCandidates who do not  pay ADMISSION FEE within the specified period will be treated as  candidates who \nare not interested in taking admission in the concerned course of study. HENCE, their allotted seat will stand \nCANC ELLED. \n \nSUBSEQUEN T ROUND S OF COUNSELL ING  AND SEAT UPGRADAT ION \n \n37.  Candidates who miss a  round  of  counselling,  due  to  any  reason  whatsoever, will  be  eligible  for \nparticipating in subseque nt rounds of  counselling provided they register and co mplete all the formalities in \nthe subsequent round. \n38.  Candidates who participate in a round of counselling but  are not offered admission will be eligible for \nparticipating in sub seque nt rounds of  counselling. They will have the option of only exercising fresh choices/ \norder of preference in the subsequent round, provided that uploaded documents are verified in prior round of \ncounselling .'),
 Document(metadata={'source': 'amu data/amu counselling guide.pdf', 'page': 13}, page_content='order of preference in the subsequent round, provided that uploaded documents are verified in prior round of \ncounselling . \n39. Candidates who have been  offered admission on a lower preference choice will be eligible for participating in \nsubsequent rounds of counselling through upgradation only if they get their admission completed against \nadmission offered to them in a given round and have submitted their willingness to upgrade to higher opted \nchoice in subsequent Rounds. However, such candidates cann ot exercise fresh cho ices/ order of preference in \nthe subseque nt round.  After successful pay of fee against allotted branch/school/subject/cent er the candidate \nhas to opt for upgradation. The upgradation will be done in order of preference given by the candidate against \navailable seats.   \n \n \n \n40.  A cand idate who had accepted the allocated seat with willingness to upgrade his admission, sh all be upgraded'),

In [21]:
chunks=[document.page_content for document in texts]

In [28]:
chunks

['Online Payments Terms & Conditions  \n \nThis online payment system is provided by Aligarh M uslim University Aligarh (AMU). The \nAMU may update these terms from time to time withou t any prior notice or reason and \nany changes will be effective immediately on being set out here. Please ensure you are \naware of the current terms. The country of domicile  for AMU is India. \nTerms & Conditions \nPlease read these terms carefully before using the online payment facility. Using the \nonline payment facility on this website indicates t hat you accept these terms. If you do \nnot accept these terms do not use this facility. AM U reserves the right to change the fees \nat any time. \nYour payment will normally reach AMU account to whi ch you are making a payment \nwithin two working days. \nWe cannot accept liability for a payment not reachi ng the correct AMU account if \npayment is refused or declined by the credit/debit card supplier for any reason. \nIf the card supplier declines payment, AMU is under  no obligation to bring this fact to \nyour attention. You should check with your bank/cre dit/debit card supplier that payment \nhas been deducted from your account. \nIn no event will AMU be liable for any damages what soever arising out of the use, \ninability to use, or the results of use of this sit e, any websites linked to this site, or the \nmaterials or information contained at any or all su ch sites, whether based on warranty, \ncontract, tort or any other legal theory and whethe r or not advised of the possibility of \nsuch damages. \nRefunds, if applicable, at the discretion of the ad ministration of the AMU, will only be \nmade to the debit/credit card used for the original  transaction. For the avoidance of \ndoubt nothing in this Policy shall require AMU to r efund the Fees (or part thereof) unless \nsuch Fees (or part thereof) have previously been pa id. \nSecurity \nAll payment details which are entered through this payment gateway are encrypted \nwhen the Student, or third party making payment, en ters them. Communications to and \nfrom the Service Provider’s site are encrypted. \nAMU shall not be liable for any failure by the Stud ent or third party making payment of \nFees to properly protect data from being seen on th eir screen by other persons or \notherwise obtained by such persons, during the onli ne payment process or in respect of \nany omission to provide accurate information in the  course of the online payment \nprocess. \nService Provider \nOnline Payments of Fees can be made by Credit / Deb it card or Net banking. These \npayments are not collected by AMU directly but thro ugh the Service Provider. \nPrivacy Policy \nThis Privacy Policy applies to all of the products,  services and websites offered by AMU. \nAMU may post product specific privacy notices or He lp Centre materials to explain our \nproducts in more detail without any prior notice. \nWebsite Detail: \nEntire content of the website has been gathered to the best of our knowledge and belief, \nand the university endeavors to keep it up to date.  In particular, we reserve the entire \nright to update and/or modify and/or remove this da ta anytime and without any prior \nnotice. Please note that AMU holds no responsibilit y for incorrect or no longer correct \nstatements, quotes or descriptions and thereby excl udes liability for any losses resulting \nfrom such wrong information. ',
 'Further, AMU has every right to bring about legal a ction on students who \nmisuse/alter/reproduce the content/ information ava ilable on the website \nData Privacy Policy \nOur data privacy policy strictly conforms as per th e regulations set down in accordance \nto the protection of data collected from people vis iting our website. AMU treats all \npersonal data obtained via internet and our website  carefully and confidentially so that \nno physical/mental harm is instilled up on the pers on, with regard to the collected data. \nPersonal data that has possibly been known to us wi ll be kept secret, privacy will be \nrespected and information will be used exclusively for the purpose for which it was made \nknown to us. \nChanges to our Privacy Policy \nAMU reserves the entire right to modify/amend/remov e this privacy statement anytime \nand without any prior notice or reason. Nothing con tained herein creates or is intended \nto create a contract/agreement between AMU and any user visiting the AMU website or \nproviding identifying information of any kind. \nArbitration and Jurisdiction \nIn the event of any dispute, the High Court, Allaha bad shall have exclusive jurisdiction \nsubject to condition that the either party shall be  entitled to refer such dispute to the sole \narbitration of the Vice-Chancellor, Aligarh Muslim University, Aligarh or his nominee who \nshall decide the dispute according to Arbitration A ct and whose decision shall be final \nand binding on the parties. In case, the nominee of  the Vice-Chancellor, Aligarh Muslim \nUniversity, Aligarh fails to act as arbitrator, the  Vice-Chancellor may change the \narbitrator, the person so nominated by the Vice-Cha ncellor will proceed further in the \narbitration from the stage the previous nominee lef t the arbitration. ',
 '1 \n REGULATIONS FOR Ph.D.  \nChapter XXV ( E) of the Ordinances (Academic)  \n \n1. Vacancy notification  \n \nThe University  shall notify the maximum number of admissions to be made in each \ndiscipline  in the ensuing academic session after leaving one-third of the total available \nseats vacant and taking i nto consideration: \n \na) The number of faculty members available in each discipline  for supervision.  \nb) The number of admissions in Ph.D. that can be made according to the prescribed  \nrules for supervision. \nc) The Library and Laboratory facilities and other essential resources available, to the \nextent this information is relevant for fixing  the nu mber of candidates who can be \nadmitted. \n \n2. Supervision  \n \n(i) Any permanent faculty member working as Professor/Associate Professor in the \nUniversity with a Ph.D., and at least five research publications in peer -reviewed or \nrefereed journals and any permanent faculty member working as Assistant Professor \nwith a Ph.D., and at least  three research publications in peer -reviewed or refereed \njournals may be recognized as a Research Supervisor  \n \nProvided that in areas/disciplines where there are no or only a limited nu mber of peer -\nreviewed or refereed journals,  the Board of Studies ( BoS)  may relax the above \ncondition for the recognition of a person as Rese arch Supervisor with reasons to be \nrecorded in writing. \n \n \n(ii) The allocation of Research Super visor for a selected research sch olar shall be   \nrecommended  by the BoS concerned depen ding on the number of sch olars per \nResearch Super visor, the available specialization of the Super visors and research \ninterests of the scholars. \n \n(iii) At any given point of time a Research Super visor who is  a Professor can guide up to \na maximum  of Eight (8) research scholars ; an Associate Professor can guide up to a \nmaximum  of Six (6) research scholars  and an Assistant Professor can guide up to a \nmaximum of Four (4) research scholars . This includes regular scholars and Persons \nwith Disability ( PwD) category scholars . \nProvided that a teacher of the University, at any point of time, can guide a maximum \nof two Foreign nationals and two part -time scholars only over and above her/his norm \nof guiding scholars given above.   \nAt any point, the total number of Ph.D. scholars und er a teacher , either as a supervisor \nor a co-supervisor, shall not exceed the number as prescribed  above.  \n \n(iv) Teachers of the University who have less than three years to retire shall not be \nrecommended for the appointment as supervisor by the BoS.  However, such teachers \ncan continue to supervise Ph.D. scholars who are already  registered until \nsuperannuation and as a co -supervisor after superannuation, but not after attaining the \nage of 70 years.  ',
 '2 \n  \n(v) In case of relocation of woman research scholar of the University due to marriage, the \nresearch data shall be allowed to be transferred to the University to which the scholar \nintends to relocate provided all the other conditions in these Regulations are followed \nin letter and spirit  and the research work does  not pertain to the project secured by \nthe University / Supervisor from any funding agency. The research scholar will, \nhowever, give due credit to the parent guide and the University  for the part of research \nalready done. \n \n2.1 Co-Supervision  \n(i) Co- Supe rvisor(s), if required, can be appointed  in inter-disciplinary areas preferably \nfrom other Departments of Studies or from other related institutions from outside the \nUniversity having comparable or higher NIRF/Times Higher Education/QS Ranking  \nwith the approval of the CASR.  \n \n(ii) Co-supervision of theses is justified in the following situations:  \na) The thesis is interdisciplinary or inter -sectoral, as it requires the respective \ncontribution of the two supervisors in different fields of knowledge. The RAC \nmust justify the contribution of both the initial supervisor and the proposed \nco-supervisor.  \nb) The thesis is under international or inter -institutional joint supervision, in that \nthe proposed co -supervisor belongs to a different institution, whether national \nor foreign, public or private.  \nc) The thesis aims to be awarded in collaboration with industry.  \n \n(iii)The teachers of the university may be permitted to guide Ph.D. scholars admitted to \nother universities of comparable or higher NIRF/Times Higher Education/QS \nRanking as a co -supervisor, provided that  \n \na) There is a vacancy with the teacher the candidate intends to work under.  \nb) The sponsoring university seeks prior permission in the matter and  \nc) The concerned BoS approves it.  \n \n3. Application for Admission  \n \n(i) Candidates can apply for admission to Full -time/Part -time Ph.D. programme in \nthe Faculties of Agricultural Sciences, Arts, Commerce, International Studies, \nLife Sciences, Science, Social Sciences, Theology, Engineering & Technology, \nLaw, Management Studies & Research, Medicine and  Unani Medicine.  \n \n(ii) Candidate eligible for admission to the Ph.D. programme  in more than one \nFaculty of the University can apply for the same but such a candidate will have \nto fill separ ate Application Form for each Faculty. However, s/he can apply only \nin a maximum of two  disciplines within the same Faculty. \n \n(iii) All candidates shall submit the duly filled Application Form on the online \nportal  of the CoE  on or before the last date announced by the University.  \n \n(iv) Exemption from appearing in the written test as per the clause 3.1(ii) -(iii) of \nChapter XXV (E) of the Ordinances (Academic) will be applicable to only those ',
 '3 \n candidates who are eligible for the same on the notified last date of submitting  of \nApplication Form and have submitted  documentary proof of the same  with their \nApplication Form.  \n \n4. Conduct of Admi ssion Test  \n \n(i) Written  Test: An eligible candidate, as per proviso 2.1 of Chapter XXV (E) of the \nOrdinances (Academic), shall be requi red to appear in the written test, except \n(a)foreign nationals and (b) those who are exempted  as per proviso 3.1(ii) . \n \n(ii) The test pape r, carrying 80 marks shall be of ninety minutes’ duration. It shall \nconsist of the following sections :  \n \nSection A:  Research Aptitude / Methodology  \nIt shall be of 45 minutes’ duration.  There shall be 40 Multiple Choice Questions \n(MCQs) of 1 mark each on Research Aptitude / Methodology. \n \nSection  B: Subject Specific  \nIt shall be of 45 minutes’ duration.  There shall be 40 Multiple Choice Questions \n(MCQs) of 1 mark each covering equitably, as far as possible, all topics of the \nsyllabus.  \n \n(iii) There shall be no negative marking.  \n \n(iv) The CoE  would request the Deans of Faculties to provide the names of the \nteachers who will be contributing questions (MCQs) to create a question pool \nfrom which the paper for Section -A shall be set and moderated.  \n \n(v) The CoE  would request the Chairman of the Department concerned to provide the \nnames of the teachers who will be contributing questions (MCQs) to create a \nquestion pool from which the paper for Section -B shall be set and moderated.  \n \n(vi) Paper for both Section -A and Se ction -B will be set in the CoE office The Dean \nof the Faculty shall be responsible for coordinating preparation of three sets of \npapers of Section A, while the Chairman of the Department concerned shall be \nresponsible for coordinating the preparation of th ree set s of papers of Section B \nas per procedure approved by the Vice -Chancellor from time to time.  \n \n(vii) The CoE shall present the above sets of papers before the Vice -Chancellor , who \nwill approve one set of paper of Section -A for each Faculty and one set of p aper \nof Se ction -B for each discipline . \n \n(viii) CoE shall be responsible for  \n \n(a) the printing of Question Booklets.  \n(b)  the conduct of the written test  \n(c)  uploading the Answer Key, and  \n(d) resolving all challenges to the Answer Key.  \n ',
 '4 \n (ix) Evaluation of the MCQs shall be done in the CoE office.  \n \n(x) Candidates should  secure 50% or more marks in the Written Test to  be eligible  for \nPresentation -cum-Interview . However, a relaxation of 5% marks shall be allowed \nfor PwD  candidates, and they should secure a minimum of 45% marks in the \nWritten Test to be eligible for Presentation -cum-Interview.  \n \n(xi) Presentation -cum-Interview:  All candidates who qualify the written test and those \nwho were exempted as per  Clause 3.1(ii) of Chapter XXV(E) of the  Ordinances \n(Academic) shall be called for Presentation -cum-Interview.   \n \nIn addition, Fo reign national candidates shall  also be required to appear for \nPresen tation-cum-Interview as per Clause 3.1(iii) of Chapter XXV(E) of the \nOrdinances (Academic).  \n \n(xii) Prese ntation-cum-Interview shall be of 20 marks and will normally be held \nwithin 1-2 weeks following the declaration of the list of candidates short -listed as \nper Clause 4(x) & (xi) of these Regulations. \n \n(xiii) Each short -listed candidate will give a prese ntation, not exceeding 15 minutes, \nrelated to his proposed area of research, and appear for an interview before the \nPresentation -cum-Interview Committee.   \n \n(xiv) The prese ntation shall be in the English language, ex cept for those appearing in \nthe Departments of Arabic, Hindi, Modern Indian Lan guages, Persi an, Sanskrit, \nUrdu, and Theology, in which the prese ntation shall be  made in the respe ctive \nlanguage or language approved by the concerned  CASR on the re commendation of \nBoS. \n \n(xv) The Prese ntation-cum-Interview Committee in each department shall consist of \nthe Chairman , two available senior most faculty members of the department and a \nnominee of the Vice -Chancellor.  \n \n(xvi) The Presentation -cum-Interview shall be open to all teachers of the Department . \nHowever,  questions shall only be asked by the Presentation -cum-Interview \nCommitt ee. \n \n(xvii)  A candidate who fails to appear for Presentation –cum-Interview shall not be \neligible for admission.  \n \n(xviii)  The Chairman of the Department concerned  shall  send the marks obtained by \nthe candidates in the Presentation -cum-Interview  in a sealed cover to the CoE to \ndetermine the overall merit list for each discipline.  \n \n5. Offer of Admission  \n \n(i) A single merit list of candidates who appeared in the Presentation -cum-Interview \nof each discipline shall be drawn by the CoE office based on aggregate of m arks \nin written test and Presentation –cum-Interview with the following break -up: ',
 '5 \n a) Written Test: 80 Marks  \nb) Presentation -cum-Interview: 20 Marks.  \n \nHowever, for candidates exempted from the Written Test as per the clause 3.1(ii)  of \nChapter XXV( E) of the Ordinances (Academic) , the weightage of Presentation -cum- \ninterview shall be considered out of  100 marks . \n \n(ii) Based on the combined merit list, candidates shall be selected for admission equal \nto number of vacancies notified in the discipline concerned, strictly on merit as per \nadmission policy of the University and notified after approval of the Vice -\nChancellor.  \n \nFurthe r, foreign nationals shall be considered for admission over and above the \nnotified seats, only  on the basis of their merit in the qualifying examination and \nPresentation –cum-Interview,  subje ct to the approval by the BoS of the synopsis of \nthe proposed research work specified  by them in their Application Form.   \n \n(iii) Provisional admission  shall  be offered  to the selected candidates and they  shall \nbe asked to complete their provisional admission  as per notified schedule and \nprocedure.  \n \n(iv) However, foreign nationals shall be allowed to block their seat as per notified \nprocedure of the University and subsequently complete the admission  within a \nperiod of six months from the date of the offer made to them, subject to the \ncandidate acquiring a research visa to pursue the Ph.D. programme.  \n \n(v) A candidate selected for admission to a part -time Ph.D. programme shall submit a \n“No Objection Certificate” from the Office of the Registrar , at the time of \nadmission clearly stating therein that:  \na) The candidate is permitted to pursue studies on a part -time basis.  \nb) His/her official duties permit him/her to devote sufficient time to research.  \n \n6.    Course Work  \n \n(i) Each provisionally admitted candidate , will have to undertake the prescribed  \ncourses  as per Clause 4 of Chapter XXV(E) of the Ordinances (Academic). \n \n(ii) Each course will have a maximum of 100 marks. The courses  will have the \nfollowing components of evaluation: \n \nSessi onal  : 30 marks \n             Examination  : 70 marks \n \n(iii) The ex amination in the courses  prescribed sh all be of two hours’ duration each.  \n \n(iv) A Ph.D. scholar has to obtain a minimum of 55% of marks in each of the \nprescribed courses in order to be eligible to continue in the pr ogramme and \nsubmit the thesis.  \n ',

# Contextual Chunk Headers (CCH)

In [22]:
import tiktoken

In [24]:
from typing import List, Dict, Any, Tuple

In [26]:
from openai import OpenAI

In [31]:
DOCUMENT_TITLE_PROMPT = """
INSTRUCTIONS
What is the title of the following document?

Your response MUST be the title of the document, and nothing else. DO NOT respond with anything else.

{document_title_guidance}

{truncation_message}

DOCUMENT
{document_text}
""".strip()

TRUNCATION_MESSAGE = """
Also note that the document text provided below is just the first ~{num_words} words of the document. That should be plenty for this task. Your response should still pertain to the entire document, not just the text provided below.
""".strip()

MAX_CONTENT_TOKENS = 4000
MODEL_NAME = "gpt-4o-mini"
TOKEN_ENCODER = tiktoken.encoding_for_model('gpt-3.5-turbo')

def make_llm_call(chat_messages: list[dict]) -> str:
    """
    Make an API call to the OpenAI language model.

    Args:
        chat_messages (list[dict]): A list of message dictionaries for the chat completion.

    Returns:
        str: The generated response from the language model.
    """
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=chat_messages,
        max_tokens=MAX_CONTENT_TOKENS,
        temperature=0.2,
    )
    return response.choices[0].message.content.strip()

def truncate_content(content: str, max_tokens: int) -> tuple[str, int]:
    """
    Truncate the content to a specified maximum number of tokens.

    Args:
        content (str): The input text to be truncated.
        max_tokens (int): The maximum number of tokens to keep.

    Returns:
        tuple[str, int]: A tuple containing the truncated content and the number of tokens.
    """
    tokens = TOKEN_ENCODER.encode(content, disallowed_special=())
    truncated_tokens = tokens[:max_tokens]
    return TOKEN_ENCODER.decode(truncated_tokens), min(len(tokens), max_tokens)

def get_document_title(chunks: List[str], document_title_guidance: str = "") -> str:
    """
    Extract the title of a document using a language model.

    Args:
        document_text (str): The text of the document.
        document_title_guidance (str, optional): Additional guidance for title extraction. Defaults to "".

    Returns:
        str: The extracted document title.
    """
    for document in chunks:
        document_text=document.page_content 
        # Truncate the content if it's too long
        document_text, num_tokens = truncate_content(document_text, MAX_CONTENT_TOKENS)
        truncation_message = TRUNCATION_MESSAGE.format(num_words=3000) if num_tokens >= MAX_CONTENT_TOKENS else ""
    
        # Prepare the prompt for title extraction
        prompt = DOCUMENT_TITLE_PROMPT.format(
            document_title_guidance=document_title_guidance,
            document_text=document_text,
            truncation_message=truncation_message
        )
        chat_messages = [{"role": "user", "content": prompt}]
        document_title = make_llm_call(chat_messages)
        chunk_w_header = f"Document Title: {document_title}\n\n{document_text}"
        document.page_content=chunk_w_header
    return chunks


if __name__ == "__main__":
    # Assuming document_text is defined elsewhere
    chunk_w_header = get_document_title(texts)
    # print(f"Document Title: {document_title}")

In [35]:
texts=chunk_w_header

In [71]:
# def rerank_documents(query: str, chunks: List[str]) -> List[float]:
#     """
#     Use Cohere Rerank API to rerank the search results.

#     Args:
#         query (str): The search query.
#         chunks (List[str]): List of document chunks to be reranked.

#     Returns:
#         List[float]: List of similarity scores for each chunk, in the original order.
#     """
#     MODEL = "rerank-english-v3.0"
#     client = cohere.Client(api_key=os.environ["CO_API_KEY"])

#     reranked_results = client.rerank(model=MODEL, query=query, documents=chunks)
#     results = reranked_results.results
#     reranked_indices = [result.index for result in results]
#     reranked_similarity_scores = [result.relevance_score for result in results]
    
#     # Convert back to order of original documents
#     similarity_scores = [0] * len(chunks)
#     for i, index in enumerate(reranked_indices):
#         similarity_scores[index] = reranked_similarity_scores[i]

#     return similarity_scores

# def compare_chunk_similarities(chunk_index: int, chunks: List[str], document_title: str, query: str) -> None:
#     """
#     Compare similarity scores for a chunk with and without a contextual header.

#     Args:
#         chunk_index (int): Index of the chunk to inspect.
#         chunks (List[str]): List of all document chunks.
#         document_title (str): Title of the document.
#         query (str): The search query to use for comparison.

#     Prints:
#         Chunk header, chunk text, query, and similarity scores with and without the header.
#     """
#     chunk_text = chunks[chunk_index]
#     chunk_wo_header = chunk_text
#     chunk_w_header = f"Document Title: {document_title}\n\n{chunk_text}"

#     similarity_scores = rerank_documents(query, [chunk_wo_header, chunk_w_header])

#     print(f"\nChunk header:\nDocument Title: {document_title}")
#     print(f"\nChunk text:\n{chunk_text}")
#     print(f"\nQuery: {query}")
#     print(f"\nSimilarity without contextual chunk header: {similarity_scores[0]:.4f}")
#     print(f"Similarity with contextual chunk header: {similarity_scores[1]:.4f}")

# # Notebook cell for execution
# # Assuming chunks and document_title are defined in previous cells
# CHUNK_INDEX_TO_INSPECT = 86
# QUERY = "Nike climate change impact"

# compare_chunk_similarities(CHUNK_INDEX_TO_INSPECT, chunks, document_title, QUERY)

In [36]:
import pandas as pd

In [37]:
t=pd.DataFrame(texts)

In [41]:
print(t[2][1])

('page_content', 'Document Title: Data Privacy Policy\n\nFurther, AMU has every right to bring about legal a ction on students who \nmisuse/alter/reproduce the content/ information ava ilable on the website \nData Privacy Policy \nOur data privacy policy strictly conforms as per th e regulations set down in accordance \nto the protection of data collected from people vis iting our website. AMU treats all \npersonal data obtained via internet and our website  carefully and confidentially so that \nno physical/mental harm is instilled up on the pers on, with regard to the collected data. \nPersonal data that has possibly been known to us wi ll be kept secret, privacy will be \nrespected and information will be used exclusively for the purpose for which it was made \nknown to us. \nChanges to our Privacy Policy \nAMU reserves the entire right to modify/amend/remov e this privacy statement anytime \nand without any prior notice or reason. Nothing con tained herein creates or is intended \nto create a contract/agreement between AMU and any user visiting the AMU website or \nproviding identifying information of any kind. \nArbitration and Jurisdiction \nIn the event of any dispute, the High Court, Allaha bad shall have exclusive jurisdiction \nsubject to condition that the either party shall be  entitled to refer such dispute to the sole \narbitration of the Vice-Chancellor, Aligarh Muslim University, Aligarh or his nominee who \nshall decide the dispute according to Arbitration A ct and whose decision shall be final \nand binding on the parties. In case, the nominee of  the Vice-Chancellor, Aligarh Muslim \nUniversity, Aligarh fails to act as arbitrator, the  Vice-Chancellor may change the \narbitrator, the person so nominated by the Vice-Cha ncellor will proceed further in the \narbitration from the stage the previous nominee lef t the arbitration. ')

In [26]:
t[1]

0      (metadata, {'source': 'amu data/terms (1).pdf'...
1      (metadata, {'source': 'amu data/terms (1).pdf'...
2      (metadata, {'source': 'amu data/phdregulation....
3      (metadata, {'source': 'amu data/phdregulation....
4      (metadata, {'source': 'amu data/phdregulation....
                             ...
381    (metadata, {'source': 'amu data/amu counsellin...
382    (metadata, {'source': 'amu data/amu counsellin...
383    (metadata, {'source': 'amu data/amu counsellin...
384    (metadata, {'source': 'amu data/amu counsellin...
385    (metadata, {'source': 'amu data/amu counsellin...
Name: 1, Length: 386, dtype: object

# chroma db

In [22]:
# chromadb is local database

In [10]:
persist_directory='guideToAddmissinVectorheader'

In [11]:
# from langchain_community.embeddings import OllamaEmbeddings
# embedding = OllamaEmbeddings()

In [14]:
from langchain_openai import OpenAIEmbeddings
from langchain_openai import OpenAI

In [15]:
embedding = OpenAIEmbeddings()

In [16]:
embedding

OpenAIEmbeddings(client=<openai.resources.embeddings.Embeddings object at 0x1205e3150>, async_client=<openai.resources.embeddings.AsyncEmbeddings object at 0x1211d5e10>, model='text-embedding-ada-002', dimensions=None, deployment='text-embedding-ada-002', openai_api_version=None, openai_api_base=None, openai_api_type=None, openai_proxy=None, embedding_ctx_length=8191, openai_api_key=SecretStr('**********'), openai_organization=None, allowed_special=None, disallowed_special=None, chunk_size=1000, max_retries=2, request_timeout=None, headers=None, tiktoken_enabled=True, tiktoken_model_name=None, show_progress_bar=False, model_kwargs={}, skip_empty=False, default_headers=None, default_query=None, retry_min_seconds=4, retry_max_seconds=20, http_client=None, http_async_client=None, check_embedding_ctx_length=True)

In [46]:
vectordb=Chroma.from_documents(documents=texts,
                               embedding=embedding,
                               persist_directory=persist_directory)

In [47]:
vectordb.persist()
vectordb=None

/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_20379/4172417374.py:1: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  vectordb.persist()

In [19]:
vectordb=Chroma(persist_directory=persist_directory,
                embedding_function=embedding)

# Make a retriever

In [20]:
retriver=vectordb.as_retriever()

In [50]:
docs=retriver.get_relevant_documents("duration of M.Sc. (Home Science)?")

/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_20379/834739747.py:1: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use invoke instead.
  docs=retriver.get_relevant_documents("duration of M.Sc. (Home Science)?")

In [51]:
len(docs)

4

In [39]:
retriever=vectordb.as_retriever(search_kwargs={"k":2})

In [40]:
retriever.search_type

'similarity'

In [41]:
retriever.search_kwargs

{'k': 2}

In [36]:
docs=retriever.get_relevant_documents("How much money did Microsoft raise?")

In [34]:
len(docs)

2

In [40]:
from langchain_core.pydantic_v1 import BaseModel, Field
from typing import List, Dict, Any, Tuple

In [38]:
from langchain.docstore.document import Document

In [39]:
from langchain_openai import ChatOpenAI

In [24]:
from langchain import PromptTemplate

In [25]:
class RatingScore(BaseModel):
    relevance_score: float = Field(..., description="The relevance score of a document to a query.")

def rerank_documents(query: str, docs: List[Document], top_n: int = 3) -> List[Document]:
    prompt_template = PromptTemplate(
        input_variables=["query", "doc"],
        template="""On a scale of 1-10, rate the relevance of the following document to the query. Consider the specific context and intent of the query, not just keyword matches.
        Query: {query}
        Document: {doc}
        Relevance Score:"""
    )
    
    llm = ChatOpenAI(temperature=0, model_name="gpt-4o", max_tokens=4000)
    llm_chain = prompt_template | llm.with_structured_output(RatingScore)
    
    scored_docs = []
    for doc in docs:
        input_data = {"query": query, "doc": doc.page_content}
        score = llm_chain.invoke(input_data).relevance_score
        try:
            score = float(score)
        except ValueError:
            score = 0  # Default score if parsing fails
        scored_docs.append((doc, score))
    
    reranked_docs = sorted(scored_docs, key=lambda x: x[1], reverse=True)
    return [doc for doc, _ in reranked_docs[:top_n]]

In [26]:
query = "what is the course code of about M.Sc. (Agriculture) Nematology?"
initial_docs = vectordb.similarity_search(query, k=15)
reranked_docs = rerank_documents(query, initial_docs)

# print first 3 initial documents
print("Top initial documents:")
for i, doc in enumerate(initial_docs[:5]):
    print(f"\nDocument {i+1}:")
    print(doc.page_content[:400] + "...")  # Print first 200 characters of each document


# Print results
print(f"Query: {query}\n")
print("Top reranked documents:")
for i, doc in enumerate(reranked_docs):
    print(f"\nDocument {i+1}:")
    print(doc.page_content[:200] + "...")  # Print first 200 characters of each document

Top initial documents:

Document 1:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.3 Course of Study  :  M.Sc. (Agriculture) Plant Pathology

Course Details  : Duration  Course Code  Intake
  4 Semesters  PPMGA  8+3*
  * Indian Council of Ag ricultural Research(ICAR) quot...

Document 2:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.2 Test Centre(s)  : The Admission Test shall be held at Aligarh (U.P.),

Additional
Information  : Note : Students admitted to B.Sc. (Hons.) Agriculture shall pay additional  charges of Rs.
...

Document 3:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.5 Note:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’
to ascertain whether s/he is permitted to apply for the course of study.

Age Limit  : Not more ...

Document 4:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.1 Faculty of Agricultural Sciences

BACHELOR’S DEGREE COURSES

Course of Study  : B.Sc. (Hons.) Community  Science

Course Details  : Duration  Course Code  Intake
  Male  Female
 ...

Document 5:
Document Title: Guide to Admissions (Supplement -FN) 2024 -25



Aligarh Muslim University                                                                                                              Guide to  Admissions (Supplement -FN) 2024 -25

Table -I: Intake and F ee Structure


FN-6

S. No. Cour se of Stu dy Intake for
ICCR Intake for
Foreign
Nationals
/ NRIs Course
Code D...
Query: what is the course code of about M.Sc. (Agriculture) Nematology?

Top reranked documents:

Document 1:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 ...

Document 2:
Document Title: Guide to Admissions (Supplement -FN) 2024 -25



Aligarh Muslim University                                                                                                            ...

Document 3:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                                                 ...

In [62]:
print("Top initial documents:")
for i, doc in enumerate(initial_docs[:3]):
    print(f"\nDocument {i+1}:")
    print(doc.page_content[:400] + "...")  # Print first 200 characters of each document


# Print results
print(f"Query: {query}\n")
print("Top reranked documents:")
for i, doc in enumerate(reranked_docs):
    print(f"\nDocument {i+1}:")
    print(doc.page_content[:400] + "...")  # Print first 200 characters of each document

Top initial documents:

Document 1:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.3 Course of Study  :  M.Sc. (Agriculture) Plant Pathology

Course Details  : Duration  Course Code  Intake
  4 Semesters  PPMGA  8+3*
  * Indian Council of Ag ricultural Research(ICAR) quot...

Document 2:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.2 Test Centre(s)  : The Admission Test shall be held at Aligarh (U.P.),

Additional
Information  : Note : Students admitted to B.Sc. (Hons.) Agriculture shall pay additional  charges of Rs.
...

Document 3:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.5 Note:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’
to ascertain whether s/he is permitted to apply for the course of study.

Age Limit  : Not more ...
Query: what is the course code of about M.Sc. (Agriculture) Nematology?

Top reranked documents:

Document 1:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25
A.3 Course of Study  :  M.Sc. (Agriculture) Plant Pathology

Course Details  : Duration  Course Code  Intake
  4 Semesters  PPMGA  8+3*
  * Indian Council of Ag ricultural Research(ICAR) quot...

Document 2:
Document Title: Guide to Admissions (Supplement -FN) 2024 -25



Aligarh Muslim University                                                                                                              Guide to  Admissions (Supplement -FN) 2024 -25

Table -I: Intake and F ee Structure


FN-6

S. No. Cour se of Stu dy Intake for
ICCR Intake for
Foreign
Nationals
/ NRIs Course
Code D...

Document 3:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                                                              Guide to Admissions 2024 -25
Appendix - X
Test Schedule  of Courses of Study

S.28
 S. No.
Name of Course  COURSE
CODE  CAT Test Schedule
Date  Duration  Scheduled
Start
Fac...

# Make a Chain

In [41]:
from langchain_core.retrievers import BaseRetriever

In [42]:
from langchain.chains import RetrievalQA

In [43]:
class CustomRetriever(BaseRetriever, BaseModel, metaclass=CombinedMeta):
    
    vectorstore: Any = Field(description="Vector store for initial retrieval")

    class Config:
        arbitrary_types_allowed = True

    def get_relevant_documents(self, query: str, num_docs=2) -> List[Document]:
        initial_docs = self.vectorstore.similarity_search(query, k=30)
        return rerank_documents(query, initial_docs, top_n=num_docs)


# Create the custom retriever
custom_retriever = CustomRetriever(vectorstore=vectordb)

# Create an LLM for answering questions
llm = ChatOpenAI(temperature=0, model_name="gpt-4o")

# Create the RetrievalQA chain with the custom retriever
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=custom_retriever,
    return_source_documents=True
)

NameError: Field name "model_config" shadows a BaseModel attribute; use a different field name with "alias='model_config'".

In [72]:
query='What are the criteria for the "DS (Distant State/UT)" category, as described in this form, and what are the options available for selecting a distant state/UT?  What constitutes a "distant state/UT" in this context?'
result = qa_chain({"query": query})

print(f"\nQuestion: {query}")
print(f"Answer: {result['result']}")
print("\nRelevant source documents:")
for i, doc in enumerate(result["source_documents"]):
    print(f"\nDocument {i+1}:")
    print(doc.page_content[:200] + "...")  # Print first 200 characters of each document

Question: What are the criteria for the "DS (Distant State/UT)" category, as described in this form, and what are the options available for selecting a distant state/UT?  What constitutes a "distant state/UT" in this context?
Answer: The criteria for the "DS (Distant State/UT)" category, as described in the document, require that the candidate's state or union territory of domicile is not adjoining the state of Uttar Pradesh, Kerala, West Bengal, or Bihar, depending on the AMU center they are applying to. To claim this category, candidates must provide an attested copy of a certificate of domicile from the district authority of the state or union territory to which they belong.

In this context, a "distant state/UT" is one that does not share a border with the state where the AMU center is located. The options available for selecting a distant state/UT are listed in Table VII of the document, which specifies the eligibility for each state or union territory for nomination under the Distant State category for courses of study at AMU, Aligarh, and its centers in Malappuram, Murshidabad, and Kishanganj.

Relevant source documents:

Document 1:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 ...

Document 2:
Document Title: Admission Guidelines and Merit Lists

 3 broken on date of birth, the preference will be given to the candidate who has attempted
fewer questions incorrectly in the Test.
b) Select ...

Document 3:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 ...

Document 4:
Document Title: Ph.D. Programme Admission Guidelines

0-2

Provided that a permanent Non -teaching employee of this University with five years of regular
service will be eligible to apply for admi...

Document 5:
Document Title: Guidelines for Admission under Sports and Debater & Talent Category


 4 7. Consideration under Outstanding Sp ortsperson / Debater and Talent
Category over and above the intake of t...

# cross encoder

In [68]:
from sentence_transformers import CrossEncoder

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <2BD1B165-EC09-3F68-BCE4-8FE4E70CA7E2> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/image.so
  Expected in:     <552B36CA-07A6-332B-BF7F-6D22D9005F71> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_cpu.dylib'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

In [69]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

class CrossEncoderRetriever(BaseRetriever, BaseModel):
    vectorstore: Any = Field(description="Vector store for initial retrieval")
    cross_encoder: Any = Field(description="Cross-encoder model for reranking")
    k: int = Field(default=5, description="Number of documents to retrieve initially")
    rerank_top_k: int = Field(default=3, description="Number of documents to return after reranking")

    class Config:
        arbitrary_types_allowed = True

    def get_relevant_documents(self, query: str) -> List[Document]:
        # Initial retrieval
        initial_docs = self.vectorstore.similarity_search(query, k=self.k)
        
        # Prepare pairs for cross-encoder
        pairs = [[query, doc.page_content] for doc in initial_docs]
        
        # Get cross-encoder scores
        scores = self.cross_encoder.predict(pairs)
        
        # Sort documents by score
        scored_docs = sorted(zip(initial_docs, scores), key=lambda x: x[1], reverse=True)
        
        # Return top reranked documents
        return [doc for doc, _ in scored_docs[:self.rerank_top_k]]

    async def aget_relevant_documents(self, query: str) -> List[Document]:
        raise NotImplementedError("Async retrieval not implemented")

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_20379/4132487303.py:3: DeprecationWarning: Retrievers must implement abstract `_get_relevant_documents` method instead of `get_relevant_documents`
  class CrossEncoderRetriever(BaseRetriever, BaseModel):
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_20379/4132487303.py:3: DeprecationWarning: Retrievers must implement abstract `_aget_relevant_documents` method instead of `aget_relevant_documents`
  class CrossEncoderRetriever(BaseRetriever, BaseModel):

In [70]:
# Create the cross-encoder retriever
cross_encoder_retriever = CrossEncoderRetriever(
    vectorstore=vectordb,
    cross_encoder=cross_encoder,
    k=10,  # Retrieve 10 documents initially
    rerank_top_k=5  # Return top 5 after reranking
)

# Set up the LLM
llm = ChatOpenAI(temperature=0, model_name="gpt-4o")

# Create the RetrievalQA chain with the cross-encoder retriever
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=cross_encoder_retriever,
    return_source_documents=True
)

# Example query
query = "what is the course code of about M.Sc. (Agriculture) Nematology?"
result = qa_chain({"query": query})

print(f"\nQuestion: {query}")
print(f"Answer: {result['result']}")
print("\nRelevant source documents:")
for i, doc in enumerate(result["source_documents"]):
    print(f"\nDocument {i+1}:")
    print(doc.page_content[:200] + "...")  # Print first 200 characters of each document

Question: what is the course code of about M.Sc. (Agriculture) Nematology?
Answer: The course code for M.Sc. (Agriculture) Nematology is NEMGA.

Relevant source documents:

Document 1:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 ...

Document 2:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                                                 ...

Document 3:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 ...

Document 4:
Document Title: Guide to Admissions 2024 -25

Aligarh Muslim University                                                                                                                                 ...

Document 5:
Document Title: Guide to Admissions (Supplement -FN) 2024 -25



Aligarh Muslim University                                                                                                            ...

In [49]:
from langchain_community.llms import Ollama
## Load Ollama LAMA2 LLM model
llm=OpenAI(temperature=0.3)
llm

OpenAI(client=<openai.resources.completions.Completions object at 0x1213f7f90>, async_client=<openai.resources.completions.AsyncCompletions object at 0x135f29a90>, temperature=0.3, openai_api_key=SecretStr('**********'), openai_proxy='')

In [50]:
from langchain.prompts import PromptTemplate

prompt_template = """Given the following context and a question, generate an answer based on this context only.
In the answer try to provide as much text as possible from "response" section in the source document context without making much changes.
If the answer is not found in the context, kindly state "I don't know." Don't try to make up an answer.

CONTEXT: {context}

QUESTION: {question}"""


PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)
chain_type_kwargs = {"prompt": PROMPT}


from langchain.chains import RetrievalQA

model = RetrievalQA.from_chain_type(llm=llm,
                            chain_type="stuff",
                            retriever=retriever,
                            input_key="query",
                            return_source_documents=True,
                            chain_type_kwargs=chain_type_kwargs)

In [51]:
## Design ChatPrompt Template
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""Given the following context and a question, generate an answer based on this context only.
In the answer try to provide as much text as possible from "response" section in the source document context without making much changes.
If the answer is not found in the context, kindly state "I don't know." Don't try to make up an answer.
<context>
{context}
</context>
Question: {input}
"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm,prompt)
"""
Retrievers: A retriever is an interface that returns documents given
 an unstructured query. It is more general than a vector store.
 A retriever does not need to be able to store documents, only to 
 return (or retrieve) them. Vector stores can be used as the backbone
 of a retriever, but there are other types of retrievers as well. 
 https://python.langchain.com/docs/modules/data_connection/retrievers/   
"""

retriever=vectordb.as_retriever()
"""
Retrieval chain:This chain takes in a user inquiry, which is then
passed to the retriever to fetch relevant documents. Those documents 
(and original inputs) are then passed to an LLM to generate a response
https://python.langchain.com/docs/modules/chains/
"""
from langchain.chains import create_retrieval_chain
retrieval_chain=create_retrieval_chain(retriever,document_chain)

In [52]:
retriever.search_type

'similarity'

In [53]:
response=retrieval_chain.invoke({"input":"what is the course code of about M.Sc. (Agriculture) Nematology"})
response

{'input': 'what is the course code of about M.Sc. (Agriculture) Nematology',
 'context': [Document(metadata={'page': 48, 'source': 'amu data/guide to admission.pdf'}, page_content='Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 \nA.3 Course of Study  :  M.Sc. (Agriculture) Plant Pathology  \n   \nCourse Details  : Duration  Course Code  Intake  \n  4 Semesters  PPMGA  8+3* \n  * Indian Council of Ag ricultural Research(ICAR) quota  \n   \nQualifying \nExamination  : B.Sc. (Agriculture) / B. Sc. (Horticulture) / B.Sc. (Forestry) / B.Sc. Life Sciences / B. Sc. \nBiosciences / B.Sc. (Hons.) Botany, B.Sc. (Hons.) Zoology / B.Sc. with Botany as one of the \nsubject with not less than 55% marks in aggregate.  \n \nNote:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 2 7 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental  Test \n   \nTest Paper Details  \n : There shall be one objective type  paper with the following components : \n1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Entomology  : 10 Marks  \n3)  Plant Pathology  : 10 Marks  \n4)  Nematology  : 10 Marks  \n \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology , \nM.Sc. (Agriculture) Plant Pathology and M.Sc. (Agriculture) Nematology in the Facult y of \nAgricultural Sciences.   \n   \nCourse of Study  :  M.Sc. (Agriculture) Nematology  \n   \nCourse Details  : Duration  Course Code  Intake  \n  4 Semesters   NEMGA  4+1* \n  * Indian Council of Ag ricultural Research(ICAR) quota  \n   \nQualifying \nExamination  : B.Sc. (Agriculture) / B. Sc. (Horticulture) / B.Sc. (Forestry) / B.Sc. Life Sciences / B. Sc. \nBiosciences / B.Sc. (Hons.) Botany, B.Sc. (Hons.) Zoology / B.Sc. with Zoology or Botany as \none of the subject with not less than 55% marks in aggregate.  \n \nNote:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 2 7 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental  Test \n   \nTest Paper Details  \n : There shall be one objective type  paper with the following components:  \n1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Entomology  : 10 Marks  \n3)  Plant Pathology  : 10 Marks  \n4)  Nematology  : 10 Marks  \n \n   \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology , \nM.Sc. (Agriculture) Plant Pathology and M.Sc. (Agriculture) Nematology in the Facult y of \nAgricultural Sciences.   \n   \nCourse of Study  : M.B.A. ( Agribusiness)  \n   \nCourse Details  : Duration  Course Code  Intake  \n  4 Semesters  ABMGA  20+6* \n  * Indian Council of Ag ricultural Research(ICAR) quota  \n   \nQualifying \nExamination  : Bachelor’s Degree  in  any discipline with at least 55% marks in aggregate.  \n '),
  Document(metadata={'page': 47, 'source': 'amu data/guide to admission.pdf'}, page_content='Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 \nA.2 Test Centre(s)  : The Admission Test shall be held at Aligarh (U.P.),  \n   \nAdditional \nInformation  : Note : Students admitted to B.Sc. (Hons.) Agriculture shall pay additional  charges of Rs. \n45000/- annually at the time of admission / start of each academic session.  \n \n   \nMASTER’S DEGREE COURSES  \n   \nCourse of Study  :  M.Sc. (Ag .) Microbiology  \n   \nCourse  Details  : Duration  Course Code  Intake  \n  4 Semester s MBMGA  10+3* \n  * Indian Council of Ag ricultural Research(ICAR) quota  \n   \nQualifying \nExamination  : B. Sc. (Agriculture) / B.Sc . (Biosciences) / B. Sc. (Microbiology) / B.Sc.(Industrial Microbiology) \n/ B. Sc.(Biochemistry) / B. Sc. (Biotechnology) / B. Sc. (Bioinformatics) / B. Sc. (Molecular \nBiology) with not less than 55% marks in aggregate.  \nOR \nB.Sc. (Life Sciences) with one of the subjects Zoology, Botany, Chemistry, Microbiology, \nBiotechnology  as main  and two as subsidiary subjects or any three subjects of equal value \nwith not less than 55% marks in aggregate as well as the main subject.  \n \nNote:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 2 7 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental  Test \n   \nTest Paper Details  \n : There shall be one multiple choice objective type paper of 100 marks comprising a total of 100 \nquestions with 30 questions on General Knowledge and General Awareness in Agricultural \nSciences and related branches of Sciences / Life Sciences and 70 questions on Botany, \nZoology, Biotechnology, Microbiol ogy, Biochemistry and Chemistry.  \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \n   \nCourse of Study  :  M.Sc. (Agriculture) Entomology  \n   \nCourse Details  : Duration  Course Code  Intake  \n  4 Semesters   ENMGA  8+3* \n  * Indian Council of Ag ricultural Research(ICAR) quota  \n   \nQualifying \nExamination  : B.Sc. (Agriculture) / B. Sc. (Horticulture) / B.Sc. (Forestry) / B.Sc. Life Sciences / B. Sc. \nBiosciences / B.Sc. (Hons.) Botany, B.Sc. (Hons.) Zoology / B.Sc. with Zoology as one of the \nsubject with not less than 55% marks in aggregate  \n  \nNote:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 2 7 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental  Test \n   \nTest Paper Details  \n : There shall be one objective type  paper with the following components:  \n1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Entomology  : 10 Marks  \n3)  Plant Pathology  : 10 Marks  \n4)  Nematology  : 10 Marks  \n \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology , \nM.Sc. (Agriculture) Plant Pathology and M.Sc. (Agriculture) Nematology in the Facult y of \nAgricultural Sciences.   \n   '),
  Document(metadata={'page': 50, 'source': 'amu data/guide to admission.pdf'}, page_content='Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 \nA.5 Note:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 2 7 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental Test.    \n   \nTest Paper Details  \n : There shall be one objective type  paper with the following components:  \n1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Floriculture & Landscap ing : 15 Marks  \n3)  Agronomy  : 15 Marks  \n \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : 1. There shall be a Combined Admission Test for admission to M.Sc. (Horticulture) \nFloriculture & Landscap ing and M.Sc. (Agriculture) Agronomy in the Faculty of \nAgricultural Sciences.   \n2.  Students admitted to this course shall  pay additional charge of Rs. 50000/ - annually   \nat the time of admission/start of each academic se ssion.  \n   \nCourse of Study  : M.Sc. (Agriculture) Agronomy     \n(Under Self Financing Scheme ) \n   \nCourse Details  : Duration  Course Code  Intake  \n  4 Semesters  AGMGA 15 \n   \nQualifying \nExamination  : 55% marks in aggregate in B.Sc. Agricul ture / Horticulture / Forestry   or its equivalent as \nrecognized by the University.   \n \nNote:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than  27 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental Test.    \n   \nTest Paper Details  \n : There shall be one objective type  paper with the following components:  \n1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Floriculture & Landscap ing : 15 Marks  \n3)  Agronomy  : 15 Marks  \n \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : 1. There shall be a Combined Admission Test for admission to M.Sc. (Horticulture) \nFloriculture & Landscap ing and M.Sc. (Agriculture) Agronomy in the Faculty of \nAgricultural Sciences.   \n2.  Students admitted to this course shall  pay additional charge of Rs. 5000 0/- annually   \nat the time of admission/start of each academic session.  \n '),
  Document(metadata={'page': 46, 'source': 'amu data/guide to admission.pdf'}, page_content='Aligarh Muslim University                                                                                                    Guide to Admissions 2024 -25 \nA.1 Faculty of Agricultural Sciences  \n \nBACHELOR’S DEGREE COURSES  \n   \nCourse of Study  : B.Sc. (Hons.) Community  Science  \n   \nCourse Details  : Duration  Course Code  Intake  \n  Male  Female  \n  8 Semesters  CSBGA  --- 30+6* \n   \nQualifying \nExamination  : Senior Secondary School Certificate in Agriculture or in Science (With Physics,  Chemistry and \nMathematics / Biology / Home Science) or an equivalent examination with 50% marks in \naggregate.  \n \nNote:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 24 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Combined University Entrance  Test (CUET) conducted by NTA . \n   \nTest Paper Details  \n : Candidates will have to attempt the following Domain/ General/  Languages Sections of CUET:  \na) English  (Section IA)  \nb) Physics (Section II)  \nc) Chemistry  (Section II)  \nd) Biology/Mathematics/Home Science  (Section II) –Any one  \n   \nAdditional \nInformation  : 1. Candidates should register on the CUET website cuet.samarth.ac.in  for appearing at the \nAdmission Test . \n2. In addition to the CUET website, the candidates have to also register on the AMU website \nwww.amucontrollerexams.com  for Admission Form, Counseling and Admission . \n3. Only those candidates who have registered for this course of study on the CUET website \nand appear ed in the Test (as per details given above) shall be eligible for Counseling and \nAdmission  \n   \nCourse of Study  : B.Sc. (Hons.) Agriculture (Under Self Financing Scheme ) \n   \nCourse Details  : Duration  Course Code  Intake  \n  8 Semesters  AGBGA  60+12* \n   \nQualifying \nExamination  : Senior Secondary School Certificate in Agriculture or in Science (With Physics,  Chemistry and \nMathematics / Biology / Home Science) or an equivalent examination with 50% marks in aggregate.  \n \nNote:  Candidate should refer to ‘ Allowe d Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 2 4 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Admission  Test.  \n   \nTest Paper Details  \n : There shall be one objective type  paper of 1 25 marks with the following components:  \nPart A \nAgriculture  : 25 Marks  \nPart B (common with B.Sc.(Hons./Research) in the Faculties of Science  & Life Sciences  \nAdmission Test)  \nSection I  English  : 25 Marks  \nSection Il  Chemistry  : 25 Marks  \nSection Ill  Physics  : 25 Marks  \nSection IV  Mathematics  : 25 Marks  \nSection V  Biology  : 25 Marks  \n \n  Note:  Sections I, II and III are compulsory. Candidates will have the choice to attempt any one \nSection from IV and V.  \n \nNote:  Canidiates have to compulsorily appear in both the Pa rts to become eligible for selection.                                  \n ')],
 'answer': 'Answer: NEMGA'}

In [46]:
response['answer']

'Answer: NEMGA'

In [ ]:
How can I challenge the answer key after an admission test?
What is the refund policy for admission fees if I withdraw from the course?
Can I apply for multiple courses at the same time?
What are the provisions for internal candidates seeking admission to AMU’s courses?
Can you explain the age limit criteria for admission to different courses at AMU?

In [61]:
response=retrieval_chain.invoke({"input":"Can you explain the age limit criteria for admission to different courses at AMU?"})

In [62]:
response['answer']

"\nAnswer: The age limit for admission to different courses at AMU varies depending on the course and the year of admission. For example, for the Bridge Course - Senior Secondary School Certificate, the age limit is not more than 24 years as on 01st July in the year of admission. For M.Sc. (Physics), the age limit is not more than 27 years as on 01st July in the year of admission. And for courses like Urdu/Theology and Malayalam/Bengali, the age limit is also not more than 27 years as on 01st July in the year of admission. However, it is important for candidates to refer to the 'Allowed Courses' section under 'Important Information & Rules' to determine if they are eligible to apply for the course."

In [50]:
response

{'input': 'what are the cratria of taking addmission in M.Sc. (Agriculture) Nematology ?',
 'context': [Document(metadata={'page': 47, 'source': 'guide to addmission.pdf'}, page_content='Additional \nInformation  : There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology , \nM.Sc. (Agriculture) Plant Pathology and M.Sc. (Agriculture) Nematology in the Facult y of \nAgricultural Sciences.'),
  Document(metadata={'page': 48, 'source': 'guide to addmission.pdf'}, page_content='1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Entomology  : 10 Marks  \n3)  Plant Pathology  : 10 Marks  \n4)  Nematology  : 10 Marks  \n \n   \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology , \nM.Sc. (Agriculture) Plant Pathology and M.Sc. (Agriculture) Nematology in the Facult y of \nAgricultural Sciences.   \n   \nCourse of Study  : M.B.A. ( Agribusiness)  \n   \nCourse Details  : Duration  Course Code  Intake  \n  4 Semesters  ABMGA  20+6* \n  * Indian Council of Ag ricultural Research(ICAR) quota  \n   \nQualifying \nExamination  : Bachelor’s Degree  in  any discipline with at least 55% marks in aggregate.'),
  Document(metadata={'page': 48, 'source': 'guide to addmission.pdf'}, page_content='Age Limit  : Not more than 2 7 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental  Test \n   \nTest Paper Details  \n : There shall be one objective type  paper with the following components : \n1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Entomology  : 10 Marks  \n3)  Plant Pathology  : 10 Marks  \n4)  Nematology  : 10 Marks  \n \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology , \nM.Sc. (Agriculture) Plant Pathology and M.Sc. (Agriculture) Nematology in the Facult y of \nAgricultural Sciences.   \n   \nCourse of Study  :  M.Sc. (Agriculture) Nematology  \n   \nCourse Details  : Duration  Course Code  Intake  \n  4 Semesters   NEMGA  4+1* \n  * Indian Council of Ag ricultural Research(ICAR) quota  \n   \nQualifying'),
  Document(metadata={'page': 47, 'source': 'guide to addmission.pdf'}, page_content='Biosciences / B.Sc. (Hons.) Botany, B.Sc. (Hons.) Zoology / B.Sc. with Zoology as one of the \nsubject with not less than 55% marks in aggregate  \n  \nNote:  Candidate should refer to ‘ Allowed Courses ’ under ‘ Important Information & Rules ’ \nto ascertain whether s/he is permitted to apply for the course of study.  \n   \nAge Limit  : Not more than 2 7 years as on  01st July  in the year of admission.  \n   \nSelection Process  : Through Departmental  Test \n   \nTest Paper Details  \n : There shall be one objective type  paper with the following components:  \n1)  General awareness in Agriculture and related \nbranches of Life Sciences / Biological Sciences  : 70 Marks  \n2)  Entomology  : 10 Marks  \n3)  Plant Pathology  : 10 Marks  \n4)  Nematology  : 10 Marks  \n \n   \nTest Centre(s)  : The Departmental Test shall be held at Aligarh (U.P.) only.              \n   \nAdditional \nInformation  : There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology ,')],
 'answer': "\nAnswer: The criteria for taking admission in M.Sc. (Agriculture) Nematology are as follows: \n1) General awareness in Agriculture and related branches of Life Sciences / Biological Sciences: 70 Marks \n2) Entomology: 10 Marks \n3) Plant Pathology: 10 Marks \n4) Nematology: 10 Marks \nTest Centre(s): The Departmental Test shall be held at Aligarh (U.P.) only. \nAdditional Information: There shall be a Combined Admission Test for admission to M.Sc. (Agriculture) Entomology, M.Sc. (Agriculture) Plant Pathology and M.Sc. (Agriculture) Nematology in the Faculty of Agricultural Sciences. \nCourse of Study: M.Sc. (Agriculture) Nematology \nCourse Details: Duration Course Code Intake 4 Semesters NEMGA 4+1* * Indian Council of Agricultural Research(ICAR) quota \nQualifying Examination: Bachelor's Degree in any discipline with at least 55% marks in aggregate. \nAge Limit: Not more than 27 years as on 01st July in the year of admission. \nSelection Process: Through Departmental Test \nTest Paper Details: There"}

In [51]:
response=retrieval_chain.invoke({"input":"What is the procudure to enroll in phd programme?"})

In [52]:
response['answer']

"\nAnswer: The procedure to enroll in a PhD programme is through an admission test. The total merit will have components of a written test and presentation-cum-interview. Candidates must have a corresponding statutory regulatory body with at least 55% marks in aggregate or its equivalent grade in a point scale wherever grading system is followed. They can also have an M.Phil. programme with at least 55% marks in aggregate or its equivalent grade, or a 4-year/8-semester bachelor's degree programme (with research) with a minimum of 75% marks in aggregate or its equivalent grade. The selection process is through an admission test, and the age limit is not less than 17 years as on 31st December in the year of admission. Candidates must also refer to the allowed courses under important information and rules to determine their eligibility. The basic steps to be followed in online submission of the application form include registering as a new user and providing a correct and functional email address."

In [24]:
## Design ChatPrompt Template
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""Given the following context and a question, generate an answer based on this context only.
You're a chatbot specializing in Indian law, particularly the Indian Penal Code (IPC). Your user seeks guidance on legal matters within the scope of the IPC.
Engage with them in a helpful and informative manner, providing accurate answers to their questions and clarifications regarding relevant legal concepts ,statutes.
Ensure your responses are clear, concise, and tailored to the specific queries posed.


In the answer try to provide as much text as possible from the source document context .
If the answer is not found in the context, kindly state "I don't know." Don't try to make up an answer.
<context>
{context}
</context>
Question: {input}
"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm,prompt)
"""
Retrievers: A retriever is an interface that returns documents given
 an unstructured query. It is more general than a vector store.
 A retriever does not need to be able to store documents, only to 
 return (or retrieve) them. Vector stores can be used as the backbone
 of a retriever, but there are other types of retrievers as well. 
 https://python.langchain.com/docs/modules/data_connection/retrievers/   
"""

retriever=vectordb.as_retriever()
"""
Retrieval chain:This chain takes in a user inquiry, which is then
passed to the retriever to fetch relevant documents. Those documents 
(and original inputs) are then passed to an LLM to generate a response
https://python.langchain.com/docs/modules/chains/
"""
from langchain.chains import create_retrieval_chain
retrieval_chain=create_retrieval_chain(retriever,document_chain)

In [25]:
response=retrieval_chain.invoke({"input":"What are the provisions of the Indian Penal Code regarding theft?"})
response

{'input': 'What are the provisions of the Indian Penal Code regarding theft?',
 'context': [Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\n[s 380] Theft in dwelling house, etc.\nWhoever commits theft in any building,1 tent or vessel, which building, tent or vessel\nis used as a human dwelling, or used for the custody of property, shall be punished\nwith imprisonment of either description for a term which may extend to seven years,\nand shall also be liable to ﬁne.\nState Amendment\nTamil Nadu.—The following amendments were made by Tamil Nadu Act No. 28 of 1993,\nSection 2.\nSection 380 of the Indian Penal Code (Central Act XLV of 1860) (hereinafter in this Part\nreferred to as the principal Act), shall be renumbered as sub-section (1) of that section\nand after sub-section (1) as so renumbered, the following sub-section shall be added,\nnamely:—\n"(2) Whoever commits theft in respect of any idol or icon in any building used as a\nplace of worship \'shall be punished with rigorous imprisonment for a term which shall', metadata={'page': 1422, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content="THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\n[s 379] Punishment for theft.\nWhoever commits theft shall be punished with imprisonment of either description for\na term which may extend to three years, or with ﬁne, or with both.\nCOMMENT—\nIn order to constitute theft ﬁve factors are essential:—\n(1)Dishonest intention to take property;\n(2)The property must be movable;\n(3)The property should be taken out of the possession of another person;\n(4)The property should be taken without the consent of that person; and\n(5)There must be some moving of the property in order to accomplish the taking of\nit.\n1. 'Intending to take dishonestly'.—Intention is the gist of the offence. The intention to\ntake dishonestly exists when the taker intends to cause wrongful gain to one person or\nwrongful loss to another person. Where, therefore, the accused acting bona ﬁde in the\ninterests of his employers ﬁnding a party of ﬁshermen poaching on his master's", metadata={'page': 1409, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\nOf the Receiving of Stolen Property\n[s 411] Dishonestly receiving stolen property.\nWhoever dishonestly receives or retains1 any stolen property, knowing or having\nreason to believe the same to be stolen property,2 shall be punished with\nimprisonment of either description for a term which may extend to three years, or with\nﬁne, or with both.\nState Amendment\nTamil Nadu.—The following amendments were made by T.N. Act No. 28 of 1993, section\n2.\nSection 411 of the principal Act shall be renumbered as sub-section (1) of that section\nand after sub-section (1) as so renumbered, the following sub-section shall be added,\nnamely—\n"(2) Whoever dishonestly receives or retains any idol or icon stolen from any building\nused as a place of worship knowing or having reason to believe the same to be stolen\nproperty shall, notwithstanding anything contained in sub-section (1), be punished with', metadata={'page': 1516, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\nOf Cheating\n[s 418] Cheating with knowledge that wrongful loss may ensue to person\nwhose interest offender is bound to protect.\nWhoever cheats with the knowledge that he is likely thereby to cause wrongful loss to\na person whose interest in the transaction to which the cheating relates, he was\nbound, either by law, or by a legal contract, to protect, shall be punished with\nimprisonment of either description for a term which may extend to three years, or with\nﬁne, or with both.\nCOMMENT—\nUnder section 418 of IPC, 1860 who ever cheats with the knowledge that is likely\nthereby to cause wrongful loss to the person whose interest in the transaction to which\nthe cheating relates he was bound either by law or by legal contract to protect, shall be\npunished with imprisonment or ﬁne or with both.545. This section applies to cases of\ncheating by guardians, trustees, solicitors, agents, and the manager of a Hindu family,', metadata={'page': 1543, 'source': 'Indian Penal Code Book.pdf'})],
 'answer': 'Answer: According to the Indian Penal Code, Chapter XVII, Section 379, whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both. In order to constitute theft, five factors are essential: dishonest intention to take property, the property must be movable, the property should be taken out of the possession of another person, the property should be taken without the consent of that person, and there must be some moving of the property in order to accomplish the taking of it.'}

In [26]:
response['answer']

'Answer: According to the Indian Penal Code, Chapter XVII, Section 379, whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both. In order to constitute theft, five factors are essential: dishonest intention to take property, the property must be movable, the property should be taken out of the possession of another person, the property should be taken without the consent of that person, and there must be some moving of the property in order to accomplish the taking of it.'

In [ ]:
According to the Indian Penal Code, Chapter XVII, Section 379 and Section 380, whoever commits theft shall be punished with imprisonment
for a term up to three years, or with fine, or both. In case of theft in a building, tent, or vessel used as a human dwelling or for custody 
of property, the punishment can extend up to seven years of imprisonment and a fine. Additionally, under Section 411, whoever dishonestly 
receives or retains any stolen property, knowing or having reason to believe the same to be stolen property, can be imprisoned
for up to three years or fined.'

In [27]:
response=retrieval_chain.invoke({"input":"Rioting, armed with deadly weapon?"})

In [28]:
response['answer']

'\nAnswer: Yes, rioting while being armed with a deadly weapon or anything that can be used as a weapon of offence is a punishable offense under section 148 of the Indian Penal Code. The punishment for this offense can be imprisonment for a term of up to three years, or a fine, or both. This is considered an aggravated form of the offense mentioned in the previous section, and the punishment is enhanced accordingly.'

In [91]:
## Design ChatPrompt Template
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""Given the following context and a question, generate an answer based on this context only.
You're a chatbot specializing in Indian law, particularly the Indian Penal Code (IPC). Your user seeks guidance on legal matters within the scope of the IPC.
Engage with them in a helpful and informative manner, providing accurate answers to their questions and clarifications regarding relevant legal concepts ,statutes and also punishment.
Ensure your responses are clear, concise, and tailored to the specific queries posed.


In the answer try to provide as much text as possible from "response" section in the source document context .
If the answer is not found in the context, kindly state "I don't know." Don't try to make up an answer.
<context>
{context}
</context>
Question: {input}
"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm,prompt)
"""
Retrievers: A retriever is an interface that returns documents given
 an unstructured query. It is more general than a vector store.
 A retriever does not need to be able to store documents, only to 
 return (or retrieve) them. Vector stores can be used as the backbone
 of a retriever, but there are other types of retrievers as well. 
 https://python.langchain.com/docs/modules/data_connection/retrievers/   
"""

retriever=vectordb.as_retriever()
"""
Retrieval chain:This chain takes in a user inquiry, which is then
passed to the retriever to fetch relevant documents. Those documents 
(and original inputs) are then passed to an LLM to generate a response
https://python.langchain.com/docs/modules/chains/
"""
from langchain.chains import create_retrieval_chain
retrieval_chain=create_retrieval_chain(retriever,document_chain)

In [92]:
response=retrieval_chain.invoke({"input":"What are the provisions of the Indian Penal Code regarding theft?"})
response

{'input': 'What are the provisions of the Indian Penal Code regarding theft?',
 'context': [Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\n[s 380] Theft in dwelling house, etc.\nWhoever commits theft in any building,1 tent or vessel, which building, tent or vessel\nis used as a human dwelling, or used for the custody of property, shall be punished\nwith imprisonment of either description for a term which may extend to seven years,\nand shall also be liable to ﬁne.\nState Amendment\nTamil Nadu.—The following amendments were made by Tamil Nadu Act No. 28 of 1993,\nSection 2.\nSection 380 of the Indian Penal Code (Central Act XLV of 1860) (hereinafter in this Part\nreferred to as the principal Act), shall be renumbered as sub-section (1) of that section\nand after sub-section (1) as so renumbered, the following sub-section shall be added,\nnamely:—\n"(2) Whoever commits theft in respect of any idol or icon in any building used as a\nplace of worship \'shall be punished with rigorous imprisonment for a term which shall', metadata={'page': 1422, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content="THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\n[s 379] Punishment for theft.\nWhoever commits theft shall be punished with imprisonment of either description for\na term which may extend to three years, or with ﬁne, or with both.\nCOMMENT—\nIn order to constitute theft ﬁve factors are essential:—\n(1)Dishonest intention to take property;\n(2)The property must be movable;\n(3)The property should be taken out of the possession of another person;\n(4)The property should be taken without the consent of that person; and\n(5)There must be some moving of the property in order to accomplish the taking of\nit.\n1. 'Intending to take dishonestly'.—Intention is the gist of the offence. The intention to\ntake dishonestly exists when the taker intends to cause wrongful gain to one person or\nwrongful loss to another person. Where, therefore, the accused acting bona ﬁde in the\ninterests of his employers ﬁnding a party of ﬁshermen poaching on his master's", metadata={'page': 1409, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\nOf the Receiving of Stolen Property\n[s 411] Dishonestly receiving stolen property.\nWhoever dishonestly receives or retains1 any stolen property, knowing or having\nreason to believe the same to be stolen property,2 shall be punished with\nimprisonment of either description for a term which may extend to three years, or with\nﬁne, or with both.\nState Amendment\nTamil Nadu.—The following amendments were made by T.N. Act No. 28 of 1993, section\n2.\nSection 411 of the principal Act shall be renumbered as sub-section (1) of that section\nand after sub-section (1) as so renumbered, the following sub-section shall be added,\nnamely—\n"(2) Whoever dishonestly receives or retains any idol or icon stolen from any building\nused as a place of worship knowing or having reason to believe the same to be stolen\nproperty shall, notwithstanding anything contained in sub-section (1), be punished with', metadata={'page': 1516, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\nOf Cheating\n[s 418] Cheating with knowledge that wrongful loss may ensue to person\nwhose interest offender is bound to protect.\nWhoever cheats with the knowledge that he is likely thereby to cause wrongful loss to\na person whose interest in the transaction to which the cheating relates, he was\nbound, either by law, or by a legal contract, to protect, shall be punished with\nimprisonment of either description for a term which may extend to three years, or with\nﬁne, or with both.\nCOMMENT—\nUnder section 418 of IPC, 1860 who ever cheats with the knowledge that is likely\nthereby to cause wrongful loss to the person whose interest in the transaction to which\nthe cheating relates he was bound either by law or by legal contract to protect, shall be\npunished with imprisonment or ﬁne or with both.545. This section applies to cases of\ncheating by guardians, trustees, solicitors, agents, and the manager of a Hindu family,', metadata={'page': 1543, 'source': 'Indian Penal Code Book.pdf'})],
 'answer': 'Answer: According to section 379 of the Indian Penal Code, whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both. In order to constitute theft, five factors are essential: dishonest intention to take property, the property must be movable, it should be taken out of the possession of another person, it should be taken without the consent of that person, and there must be some moving of the property in order to accomplish the taking of it.'}

In [93]:
response['answer']

'Answer: According to section 379 of the Indian Penal Code, whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both. In order to constitute theft, five factors are essential: dishonest intention to take property, the property must be movable, it should be taken out of the possession of another person, it should be taken without the consent of that person, and there must be some moving of the property in order to accomplish the taking of it.'

In [ ]:
'Answer: According to section 379 of the Indian Penal Code, whoever commits theft shall be punished with imprisonment, fine, or both. 
To constitute theft, there must be a dishonest intention to take property, the property must be movable, it must be taken without the 
consent of the owner, and there must be some movement of the property. Additionally, section 411 states that whoever dishonestly receives
or retains stolen property shall also be punished. And under section 418, anyone who cheats with the knowledge of causing wrongful loss to
a person whose interest they are bound to protect shall also face punishment.'

In [ ]:
According to the Indian Penal Code, Chapter XVII, Section 379 and Section 380, whoever commits theft shall be punished with imprisonment
for a term up to three years, or with fine, or both. In case of theft in a building, tent, or vessel used as a human dwelling or for custody 
of property, the punishment can extend up to seven years of imprisonment and a fine. Additionally, under Section 411, whoever dishonestly 
receives or retains any stolen property, knowing or having reason to believe the same to be stolen property, can be imprisoned
for up to three years or fined.'

In [115]:
llm =Ollama(model="llama3")
from langchain_core.output_parsers import StrOutputParser
prompt=ChatPromptTemplate.from_messages(
    [
        ("system","You are a helpful assistant. Please responce to the user queries"),
        ("user","Question:{question}")
    ]
)
output_parser=StrOutputParser()
chain=prompt|llm|output_parser

In [116]:
chain.invoke({"question":"hii"})

KeyboardInterrupt:

In [107]:
llm2.invoke("hii")

KeyboardInterrupt:

In [108]:
## Design ChatPrompt Template

from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""Given the following context and a question, generate an answer based on this context only.
You're a chatbot specializing in Indian law, particularly the Indian Penal Code (IPC). Your user seeks guidance on legal matters within the scope of the IPC.
Engage with them in a helpful and informative manner, providing accurate answers to their questions and clarifications regarding relevant legal concepts ,statutes and also punishment.
Ensure your responses are clear, concise, and tailored to the specific queries posed.


In the answer try to provide as much text as possible from "response" section in the source document context .
If the answer is not found in the context, kindly state "I don't know." Don't try to make up an answer.
<context>
{context}
</context>
Question: {input}
"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm2,prompt)
"""
Retrievers: A retriever is an interface that returns documents given
 an unstructured query. It is more general than a vector store.
 A retriever does not need to be able to stoe documents, only to 
 return (or retrieve) them. Vector stores can be used as the backbone
 of a retriever, but there are other types of retrievers as well. 
 https://python.langchain.com/docs/modules/data_connection/retrievers/   
"""

retriever=vectordb.as_retriever()
"""
Retrieval chain:This chain takes in a user inquiry, which is then
passed to the retriever to fetch relevant documents. Those documents 
(and original inputs) are then passed to an LLM to generate a response
https://python.langchain.com/docs/modules/chains/
"""
from langchain.chains import create_retrieval_chain
retrieval_chain=create_retrieval_chain(retriever,document_chain)

In [109]:
response=retrieval_chain.invoke({"input":"What are the provisions of the Indian Penal Code regarding theft?"})
response

{'input': 'What are the provisions of the Indian Penal Code regarding theft?',
 'context': [Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\n[s 380] Theft in dwelling house, etc.\nWhoever commits theft in any building,1 tent or vessel, which building, tent or vessel\nis used as a human dwelling, or used for the custody of property, shall be punished\nwith imprisonment of either description for a term which may extend to seven years,\nand shall also be liable to ﬁne.\nState Amendment\nTamil Nadu.—The following amendments were made by Tamil Nadu Act No. 28 of 1993,\nSection 2.\nSection 380 of the Indian Penal Code (Central Act XLV of 1860) (hereinafter in this Part\nreferred to as the principal Act), shall be renumbered as sub-section (1) of that section\nand after sub-section (1) as so renumbered, the following sub-section shall be added,\nnamely:—\n"(2) Whoever commits theft in respect of any idol or icon in any building used as a\nplace of worship \'shall be punished with rigorous imprisonment for a term which shall', metadata={'page': 1422, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content="THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\n[s 379] Punishment for theft.\nWhoever commits theft shall be punished with imprisonment of either description for\na term which may extend to three years, or with ﬁne, or with both.\nCOMMENT—\nIn order to constitute theft ﬁve factors are essential:—\n(1)Dishonest intention to take property;\n(2)The property must be movable;\n(3)The property should be taken out of the possession of another person;\n(4)The property should be taken without the consent of that person; and\n(5)There must be some moving of the property in order to accomplish the taking of\nit.\n1. 'Intending to take dishonestly'.—Intention is the gist of the offence. The intention to\ntake dishonestly exists when the taker intends to cause wrongful gain to one person or\nwrongful loss to another person. Where, therefore, the accused acting bona ﬁde in the\ninterests of his employers ﬁnding a party of ﬁshermen poaching on his master's", metadata={'page': 1409, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\nOf the Receiving of Stolen Property\n[s 411] Dishonestly receiving stolen property.\nWhoever dishonestly receives or retains1 any stolen property, knowing or having\nreason to believe the same to be stolen property,2 shall be punished with\nimprisonment of either description for a term which may extend to three years, or with\nﬁne, or with both.\nState Amendment\nTamil Nadu.—The following amendments were made by T.N. Act No. 28 of 1993, section\n2.\nSection 411 of the principal Act shall be renumbered as sub-section (1) of that section\nand after sub-section (1) as so renumbered, the following sub-section shall be added,\nnamely—\n"(2) Whoever dishonestly receives or retains any idol or icon stolen from any building\nused as a place of worship knowing or having reason to believe the same to be stolen\nproperty shall, notwithstanding anything contained in sub-section (1), be punished with', metadata={'page': 1516, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVII OF OFFENCES AGAINST PROPERTY\nOf Theft\nOf Cheating\n[s 418] Cheating with knowledge that wrongful loss may ensue to person\nwhose interest offender is bound to protect.\nWhoever cheats with the knowledge that he is likely thereby to cause wrongful loss to\na person whose interest in the transaction to which the cheating relates, he was\nbound, either by law, or by a legal contract, to protect, shall be punished with\nimprisonment of either description for a term which may extend to three years, or with\nﬁne, or with both.\nCOMMENT—\nUnder section 418 of IPC, 1860 who ever cheats with the knowledge that is likely\nthereby to cause wrongful loss to the person whose interest in the transaction to which\nthe cheating relates he was bound either by law or by legal contract to protect, shall be\npunished with imprisonment or ﬁne or with both.545. This section applies to cases of\ncheating by guardians, trustees, solicitors, agents, and the manager of a Hindu family,', metadata={'page': 1543, 'source': 'Indian Penal Code Book.pdf'})],
 'answer': " Thank you for reaching out to me. I'm here to help you with any questions or concerns you may have regarding the Indian Penal Code (IPC). Please provide more details on what specifically you want to know about theft, and I will do my best to assist you."}

In [38]:
type(response['answer'])

str

In [ ]:
response

In [76]:
from langchain.chains import RetrievalQA

In [77]:
qa_chain=RetrievalQA.from_chain_type(llm=OpenAI(),
                                     chain_type="stuff",
                                     retriever=retriever,
                                     return_source_documents=True)

In [78]:
query="punishment of murder?"
llm_responce=qa_chain(query)
llm_responce

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.0 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(

{'query': 'punishment of murder?',
 'result': ' The punishment for murder is either death or imprisonment for life and also a fine.',
 'source_documents': [Document(page_content='State of MP, (2008) 12 SCC 270 [LNIND 2008 SC 2798] .\nThe punishment for murder is either death or imprisonment for life and also ﬁne. The\nSupreme Court has, in a long course of decisions, made it an established principle that\nthe normal punishment for murder is life imprisonment and that "death" should be\nawarded in "rarest of rare cases". Examples of such rarest of rare cases are:\nLeading cases:—Kehar Singh v State (Delhi Administration). Lichhmadevi v State of\nRajasthan.\nAn abnormal delay in executing a death sentence has been recognised as a ground for\nconverting death sentence into life imprisonment.\nLeading cases:—Bachan Singh v State of Punjab Triveniben v State of Gujarat Madhu\nMehta v UOI.\nThe Supreme Court has noted serious changes which have taken place in the state of\nthe society since the categories for award of death sentence were laid down. Because\nof such changes, there should be some ﬂexibility in the application of the categories.', metadata={'page': 1832, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER XVI OF OFFENCES AFFECTING THE HUMAN BODY OF\nOFFENCES AFFECTING LIFE\n[s 302] Punishment for murder.\nWhoever commits murder shall be punished with death, or 196.[imprisonment for life],\nand shall also be liable to ﬁne.\nCOMMENT.—\nSection 302 provides the punishment for murder. It stipulates a punishment of death or\nimprisonment for life and ﬁne. Once an offender is found by the Court to be guilty of\nthe offence of murder under section 302, then it has to sentence the offender to either\ndeath or for imprisonment for life. The Court has no power to impose any lesser\nsentence.\n[s 302.1] Punishment for murder.—Evolution.—\nCr PC, 1898 had section 376(5) which required that if an accused is convicted of an\noffence punishable with death and the Court sentences him with any punishment other\nthan death, the Court shall, in its judgment, give reasons why death sentence was not\npassed. The provision of section 367(5) of the 1898 Code reads as follows:', metadata={'page': 1076, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='life imprisonment for the major offence of murder.282. In a case arising out of partition\nbetween two brothers, one of them (the accused) killed his brother, his wife and\nchildren. He was frustrated over his failure to resist partition of joint property. The\nCourt agreed that it was a heinous and brutal crime, but was not in the category of\nrarest of rare cases. The accused did not have any criminal tendency. He was a State\nGovernment employee and not a menace to the society. The Court directed his death\nsentence to be reduced to 20 years actual imprisonment including the period already\nundergone.283.\nIn a rape and murder case of an 11-year-old child, there was extra judicial confession\nmade to a senior person to seek his help. He indicated the place where the body of the\ngirl was lying. He struck her in the head twice over with a brick and then in the mouth\nonly when she threatened to disclose. This showed that he had no intention to commit', metadata={'page': 1089, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content="the death of a living child, if any part of that child has been brought forth, though the\nchild may not have breathed or been completely born (Explanation 3).\nIf death is caused by the voluntary act of the deceased resulting from fear of violence\non the part of the offender, the offence will be murder. For instance, if four or ﬁve\npersons were to stand round a man, and so threaten him and frighten him as to make\nhim believe that his life was in danger, and he were to back away from them and tumble\nover a precipice to avoid them, the persons threatening him will be guilty of murder.\nWhere the attack was aimed at one person but it fell upon another resulting in the\nlatter's death, it was held that under the doctrine of transfer of malice, the attacker\nwould be guilty of murder. Nagaraj v State, (2006) Cr LJ 3724 (Mad—FB); Rahimbux v\nState of MP, (2008) 12 SCC 270 [LNIND 2008 SC 2798] .\nThe punishment for murder is either death or imprisonment for life and also ﬁne. The", metadata={'page': 1832, 'source': 'Indian Penal Code Book.pdf'})]}

In [79]:
query="Rioting, armed with deadly weapon"
llm_responce=qa_chain(query)
llm_responce

{'query': 'Rioting, armed with deadly weapon',
 'result': ' Rioting with a deadly weapon is considered an offence against public tranquillity under the Indian Penal Code, specifically under section 148. This includes using a deadly weapon to participate in a riot or incite violence.',
 'source_documents': [Document(page_content='THE INDIAN PENAL CODE\nCHAPTER VIII OF OFFENCES AGAINST THE PUBLIC TRANQUILLITY\nThe offences in this chapter may be classiﬁed in the following four groups:—\nI. Unlawful assembly.\n(1)Being a member of an unlawful assembly (sections 141, 142, 143).\n(2)Joining an unlawful assembly armed with deadly weapons (section 144).\n(3)Joining or continuing in an unlawful assembly knowing it has been commanded\nto disperse (section 145).\n(4)Hiring of persons to join an unlawful assembly (section 150).\n(5)Harbouring persons hired for an unlawful assembly (section 157).\n(6)Being hired to take part in an unlawful assembly (section 158).\nII. Rioting (sections 146, 147).\n(1)Rioting with deadly weapon (section 148).\n(2)Assaulting or obstructing a public servant in the suppression of a riot (section\n152).\n(3)Wantonly giving provocation with intent to cause riot (section 153).\n(4)Liability of the owner or occupier of land on which an unlawful assembly is held\nor a riot is committed (section 154).', metadata={'page': 549, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER VIII OF OFFENCES AGAINST THE PUBLIC TRANQUILLITY\nThe offences in this chapter may be classiﬁed in the following four groups:—\nI. Unlawful assembly.\n(1)Being a member of an unlawful assembly (sections 141, 142, 143).\n(2)Joining an unlawful assembly armed with deadly weapons (section 144).\n(3)Joining or continuing in an unlawful assembly knowing it has been commanded\nto disperse (section 145).\n(4)Hiring of persons to join an unlawful assembly (section 150).\n(5)Harbouring persons hired for an unlawful assembly (section 157).\n(6)Being hired to take part in an unlawful assembly (section 158).\nII. Rioting (sections 146, 147).\n(1)Rioting with deadly weapon (section 148).\n(2)Assaulting or obstructing a public servant in the suppression of a riot (section\n152).\n(3)Wantonly giving provocation with intent to cause riot (section 153).\n(4)Liability of the owner or occupier of land on which an unlawful assembly is held\nor a riot is committed (section 154).', metadata={'page': 532, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER VIII OF OFFENCES AGAINST THE PUBLIC TRANQUILLITY\nThe offences in this chapter may be classiﬁed in the following four groups:—\nI. Unlawful assembly.\n(1)Being a member of an unlawful assembly (sections 141, 142, 143).\n(2)Joining an unlawful assembly armed with deadly weapons (section 144).\n(3)Joining or continuing in an unlawful assembly knowing it has been commanded\nto disperse (section 145).\n(4)Hiring of persons to join an unlawful assembly (section 150).\n(5)Harbouring persons hired for an unlawful assembly (section 157).\n(6)Being hired to take part in an unlawful assembly (section 158).\nII. Rioting (sections 146, 147).\n(1)Rioting with deadly weapon (section 148).\n(2)Assaulting or obstructing a public servant in the suppression of a riot (section\n152).\n(3)Wantonly giving provocation with intent to cause riot (section 153).\n(4)Liability of the owner or occupier of land on which an unlawful assembly is held\nor a riot is committed (section 154).', metadata={'page': 595, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='THE INDIAN PENAL CODE\nCHAPTER VIII OF OFFENCES AGAINST THE PUBLIC TRANQUILLITY\nThe offences in this chapter may be classiﬁed in the following four groups:—\nI. Unlawful assembly.\n(1)Being a member of an unlawful assembly (sections 141, 142, 143).\n(2)Joining an unlawful assembly armed with deadly weapons (section 144).\n(3)Joining or continuing in an unlawful assembly knowing it has been commanded\nto disperse (section 145).\n(4)Hiring of persons to join an unlawful assembly (section 150).\n(5)Harbouring persons hired for an unlawful assembly (section 157).\n(6)Being hired to take part in an unlawful assembly (section 158).\nII. Rioting (sections 146, 147).\n(1)Rioting with deadly weapon (section 148).\n(2)Assaulting or obstructing a public servant in the suppression of a riot (section\n152).\n(3)Wantonly giving provocation with intent to cause riot (section 153).\n(4)Liability of the owner or occupier of land on which an unlawful assembly is held\nor a riot is committed (section 154).', metadata={'page': 607, 'source': 'Indian Penal Code Book.pdf'})]}

In [80]:
def process_llm_response(llm_response):
    print(llm_response['result'])
    print('\n\n Sources:')
    for source in llm_response["source_documents"]:
        print(source.metadata['source'])

In [81]:
process_llm_response(llm_responce)

 Rioting with a deadly weapon is considered an offence against public tranquillity under the Indian Penal Code, specifically under section 148. This includes using a deadly weapon to participate in a riot or incite violence.


 Sources:
Indian Penal Code Book.pdf
Indian Penal Code Book.pdf
Indian Penal Code Book.pdf
Indian Penal Code Book.pdf

In [94]:
query = "What are the provisions of the Indian Penal Code regarding theft?"
llm_response = qa_chain(query)
process_llm_response(llm_response)

 The Indian Penal Code has several sections that deal with theft. Section 379 states that whoever commits theft shall be punished with imprisonment of up to three years, or with a fine, or both. Section 380 specifies that if the theft is committed in a building, tent, or vessel that is used as a human dwelling or for the custody of property, the punishment can extend up to seven years of imprisonment and a fine. Additionally, Tamil Nadu has a state amendment that adds a sub-section (2) to Section 380, which states that theft of an idol or icon from a place of worship can lead to rigorous imprisonment for an unspecified term. Section 411 deals with the receiving of stolen property, stating that whoever knowingly receives or retains stolen property can be punished with up to three years of imprisonment, a fine, or both. Similarly, Tamil Nadu has a state amendment to this section as well, adding a sub-section (2) that specifies punishment for receiving stolen idols or icons from a place of worship. Finally, Section 418 addresses cheating with the knowledge that it may cause wrongful loss to a person whose interest in the transaction the offender was bound to protect. This can lead to imprisonment of up to three years, a fine, or both.


 Sources:
Indian Penal Code Book.pdf
Indian Penal Code Book.pdf
Indian Penal Code Book.pdf
Indian Penal Code Book.pdf

In [ ]:
from transformers import MarianMTModel, MarianTokenizer

model_name = 'Helsinki-NLP/opus-mt-en-hi'
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

text = "Hello, how are you?"
input_ids = tokenizer.encode(text, return_tensors="pt")
output = model.generate(input_ids, max_length=100, num_beams=5, early_stopping=True)

translated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print(translated_text)

In [33]:
import torch
from IndicTransTokenizer import IndicProcessor
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

ip = IndicProcessor(inference=True)
tokenizer = AutoTokenizer.from_pretrained("ai4bharat/indictrans2-en-indic-dist-200M", trust_remote_code=True)
model = AutoModelForSeq2SeqLM.from_pretrained("ai4bharat/indictrans2-en-indic-dist-200M", trust_remote_code=True)

sentences = [
    "This is a test sentence.",
    "This is another longer different test sentence.",
    "Please send an SMS to 9876543210 and an email on newemail123@xyz.com by 15th October, 2023.",
]

batch = ip.preprocess_batch(sentences, src_lang="eng_Latn", tgt_lang="hin_Deva")
batch = tokenizer(batch, padding="longest", truncation=True, max_length=256, return_tensors="pt")

with torch.inference_mode():
    outputs = model.generate(**batch, num_beams=5, num_return_sequences=1, max_length=256)

with tokenizer.as_target_tokenizer():
    # This scoping is absolutely necessary, as it will instruct the tokenizer to tokenize using the target vocabulary.
    # Failure to use this scoping will result in gibberish/unexpected predictions as the output will be de-tokenized with the source vocabulary instead.
    outputs = tokenizer.batch_decode(outputs, skip_special_tokens=True, clean_up_tokenization_spaces=True)

outputs = ip.postprocess_batch(outputs, lang="hin_Deva")
print(outputs)

# >>> ['यह एक परीक्षण वाक्य है।', 'यह एक और लंबा अलग परीक्षण वाक्य है।', 'कृपया 9876543210 पर एक एस. एम. एस. भेजें और 15 अक्टूबर, 2023 तक newemail123@xyz.com पर एक ईमेल भेजें।']

ModuleNotFoundError: No module named 'IndicTransTokenizer'

In [35]:
import streamlit as st
from streamlit_webrtc import webrtc_streamer, VideoTransformer
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types

class SpeechToTextTransformer(VideoTransformer):
    def __init__(self):
        self.client = speech.SpeechClient()

    def transform(self, frame):
        audio_content = frame.to_ndarray(format="wav")
        audio = types.RecognitionAudio(content=audio_content)
        config = types.RecognitionConfig(
            encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
            sample_rate_hertz=frame.sample_rate,
            language_code="en-US",
        )
        response = self.client.recognize(config=config, audio=audio)
        for result in response.results:
            st.text(result.alternatives[0].transcript)

webrtc_streamer(key="example", video_transformer_factory=SpeechToTextTransformer)

ERROR: Could not find a version that satisfies the requirement IndicTransTokenizer (from versions: none)
ERROR: No matching distribution found for IndicTransTokenizer
Note: you may need to restart the kernel to use updated packages.

In [36]:
import torch
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
)
from IndicTransTokenizer import IndicProcessor


model_name = "ai4bharat/indictrans2-en-indic-1B"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

model = AutoModelForSeq2SeqLM.from_pretrained(model_name, trust_remote_code=True)

ip = IndicProcessor(inference=True)

input_sentences = [
    "When I was young, I used to go to the park every day.",
    "We watched a new movie last week, which was very inspiring.",
    "If you had met me at that time, we would have gone out to eat.",
    "My friend has invited me to his birthday party, and I will give him a gift.",
]

src_lang, tgt_lang = "eng_Latn", "hin_Deva"

batch = ip.preprocess_batch(
    input_sentences,
    src_lang=src_lang,
    tgt_lang=tgt_lang,
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Tokenize the sentences and generate input encodings
inputs = tokenizer(
    batch,
    truncation=True,
    padding="longest",
    return_tensors="pt",
    return_attention_mask=True,
).to(DEVICE)

# Generate translations using the model
with torch.no_grad():
    generated_tokens = model.generate(
        **inputs,
        use_cache=True,
        min_length=0,
        max_length=256,
        num_beams=5,
        num_return_sequences=1,
    )

# Decode the generated tokens into text
with tokenizer.as_target_tokenizer():
    generated_tokens = tokenizer.batch_decode(
        generated_tokens.detach().cpu().tolist(),
        skip_special_tokens=True,
        clean_up_tokenization_spaces=True,
    )

# Postprocess the translations, including entity replacement
translations = ip.postprocess_batch(generated_tokens, lang=tgt_lang)

for input_sentence, translation in zip(input_sentences, translations):
    print(f"{src_lang}: {input_sentence}")
    print(f"{tgt_lang}: {translation}")

ModuleNotFoundError: No module named 'IndicTransTokenizer'

In [40]:
pip install deep_translator

Collecting deep_translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from deep_translator) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from deep_translator) (2.31.0)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2024.2.2)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.1 MB/s eta 0:00:00
Installing collected packages: deep_translator
Successfully installed deep_translator-1.11.4
Note: you may need to restart the kernel to use updated packages.

In [41]:
import os
import json
from deep_translator import GoogleTranslator

In [44]:
translator = GoogleTranslator(source='auto', target='hi')

In [48]:
print(translator.translate('''According to the Indian Penal Code (IPC),
Section 441 states that whoever enters into or upon property in the possession of another with intent to commit an offence or to intimidate, 
insult or annoy any person in possession of such property, or having lawfully entered into or upon such property, unlawfully remains there 
with intent thereby to intimidate, insult or annoy any such person, or with intent to commit an offence, is said to commit "criminal trespass".
Therefore, building a house on land assigned for a shop in a colony without proper authorization would be considered as criminal trespass and
is punishable under the IPC.It is important to obtain proper permission and follow the designated land use regulations to avoid any legal consequences.'''))

भारतीय दंड संहिता (आईपीसी) के अनुसार,
धारा 441 में कहा गया है कि जो कोई अपराध करने या डराने-धमकाने के इरादे से किसी दूसरे की संपत्ति में प्रवेश करता है या उसके कब्जे में है।
ऐसी संपत्ति पर कब्ज़ा करने वाले, या ऐसी संपत्ति में कानूनी रूप से प्रवेश करने वाले या उस पर अवैध रूप से रहने वाले किसी भी व्यक्ति का अपमान या परेशान करना
ऐसे किसी भी व्यक्ति को डराने, अपमानित करने या परेशान करने के इरादे से, या अपराध करने के इरादे से, "आपराधिक अतिचार" कहा जाता है।
इसलिए, उचित प्राधिकरण के बिना किसी कॉलोनी में दुकान के लिए आवंटित भूमि पर घर का निर्माण आपराधिक अतिचार माना जाएगा और
आईपीसी के तहत दंडनीय है। किसी भी कानूनी परिणाम से बचने के लिए उचित अनुमति प्राप्त करना और निर्दिष्ट भूमि उपयोग नियमों का पालन करना महत्वपूर्ण है।

In [6]:
from nltk.translate.bleu_score import corpus_bleu
from sklearn.metrics import recall_score
import numpy as np

def calculate_recall(actual_responses, predicted_responses):
    """
    Calculate recall score for the chatbot.
    """
    return recall_score(actual_responses, predicted_responses, average='micro')

def calculate_mmr(actual_responses, predicted_responses):
    """
    Calculate Mean Reciprocal Rank for the chatbot.
    """
    mmr = 0
    for actual_response, predicted_response in zip(actual_responses, predicted_responses):
        if actual_response in predicted_response:
            mmr += 1 / (predicted_response.index(actual_response) + 1)
    return mmr / len(actual_responses)

from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction

def calculate_bleu(actual_responses, predicted_responses):
    """
    Calculate BLEU score for the chatbot.
    """
    references = [[response.split()] for response in actual_responses]
    hypotheses = [response.split() for response in predicted_responses]
    smooth = SmoothingFunction().method4  # Choose the smoothing function
    return corpus_bleu(references, hypotheses, smoothing_function=smooth)


# Example usage
actual_responses = ["In a residential colony, if a place is assigned for commercial purposes by the Municipal Authority or Land Revenue Deptt, construction of a residential building on that plot is impermissible and not allowed. Once the matter is brought to the notice of the concerned authority, the concerned landowner shall face the legal consequences for unauthorized construction including demolition of the constructed building if it is not built for commercial purposes."]
predicted_responses = ["According to Section 52 of the Indian Penal Code, any person who knowingly or intentionally makes any construction on land which is assigned for a different purpose, such as a shop in a colony, without the consent of the appropriate authority, may be punished with imprisonment of up to three months, or a fine, or both. Therefore, it is not advisable to build a house on land assigned for a shop in a colony without proper authorization. It is important to follow the designated land use and obtain the necessary permissions before undertaking any construction."]

recall = calculate_recall(actual_responses, predicted_responses)
mmr = calculate_mmr(actual_responses, predicted_responses)
bleu = calculate_bleu(actual_responses, predicted_responses)

print("Recall:", recall)
print("MMR:", mmr)
print("BLEU Score:", bleu)

Recall: 0.0
MMR: 0.0
BLEU Score: 0.03692779798019518

In [1]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')

# Sample data
data = ["The movie is awesome. It was a good thriller",
		"We are learning NLP throughg GeeksforGeeks",
		"The baby learned to walk in the 5th month itself"]

# Tokenizing the data
tokenized_data = [word_tokenize(document.lower()) for document in data]

# Creating TaggedDocument objects
tagged_data = [TaggedDocument(words=words, tags=[str(idx)])
			for idx, words in enumerate(tokenized_data)]


# Training the Doc2Vec model
model = Doc2Vec(vector_size=100, window=2, min_count=1, workers=4, epochs=1000)
model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count,
			epochs=model.epochs)

# Infer vector for a new document
new_document = "The baby was laughing and palying"
print('Original Document:', new_document)

inferred_vector = model.infer_vector(word_tokenize(new_document.lower()))

# Find most similar documents
similar_documents = model.dv.most_similar(
	[inferred_vector], topn=len(model.dv))

# Print the most similar documents
for index, score in similar_documents:
	print(f"Document {index}: Similarity Score: {score}")
	print(f"Document Text: {data[int(index)]}")
	print()

ImportError: cannot import name 'triu' from 'scipy.linalg' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/linalg/__init__.py)

In [8]:
#!pip install -U sentence-transformers

from scipy.spatial import distance
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

# Sample sentence
sentences = ["When both of you and your sons are interested in staying with your errant husband despite his mental and physical tortures, you may consult with a family counselor or psychiatrist to resolve the issue in-house before opting for legal remedies that involve more complexities and lengthy processes. Sometimes, proper counseling or mediation resolves the issues faster and more smoothly than litigation."]

test="According to Section 498A of the Indian Penal Code, any husband or relative of the husband who subjects a woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine. This includes mental as well as physical torture. You can file a complaint with the police and they will take necessary action. You can also seek help from a lawyer to file for divorce or seek protection under the Protection of Women from Domestic Violence Act, 2005. It is important to document any evidence of the torture and seek help as soon as possible."

print('Test sentence:',test)
test_vec = model.encode([test])[0]


for sent in sentences:
	similarity_score = 1-distance.cosine(test_vec, model.encode([sent])[0])
	print(f'\nFor {sent}\nSimilarity Score = {similarity_score} ')

Test sentence: According to Section 498A of the Indian Penal Code, any husband or relative of the husband who subjects a woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine. This includes mental as well as physical torture. You can file a complaint with the police and they will take necessary action. You can also seek help from a lawyer to file for divorce or seek protection under the Protection of Women from Domestic Violence Act, 2005. It is important to document any evidence of the torture and seek help as soon as possible.

For When both of you and your sons are interested in staying with your errant husband despite his mental and physical tortures, you may consult with a family counselor or psychiatrist to resolve the issue in-house before opting for legal remedies that involve more complexities and lengthy processes. Sometimes, proper counseling or mediation resolves the issues faster and more smoothly than litigation.
Similarity Score = 0.49775516986846924

In [ ]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [10]:
pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer, util
# sentences = ["I'm happy", "I'm full of happiness"]
sentences = ["In a residential colony, if a place is assigned for commercial purposes by the Municipal Authority or Land Revenue Deptt, construction of a residential building on that plot is impermissible and not allowed. Once the matter is brought to the notice of the concerned authority, the concerned landowner shall face the legal consequences for unauthorized construction including demolition of the constructed building if it is not built for commercial purposes."]
test = "According to Section 52 of the Indian Penal Code, any person who knowingly or intentionally makes any construction on land which is assigned for a different purpose, such as a shop in a colony, without the consent of the appropriate authority, may be punished with imprisonment of up to three months, or a fine, or both. Therefore, it is not advisable to build a house on land assigned for a shop in a colony without proper authorization. It is important to follow the designated land use and obtain the necessary permissions before undertaking any construction."


model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

#Compute embedding for both lists
embedding_1= model.encode(sentences, convert_to_tensor=True)
embedding_2 = model.encode(test, convert_to_tensor=True)

util.pytorch_mrr(embedding_1, embedding_2)
## tensor([[0.6003]])

AttributeError: module 'sentence_transformers.util' has no attribute 'pytorch_mrr'

In [115]:
import os
os.environ['OPENAI_API_KEY']='YOUR_OPENAI_API_KEY_HERE'
from langchain_core.output_parsers import StrOutputParser
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings
from langchain_openai import OpenAI
import streamlit as st
from deep_translator import GoogleTranslator
translator = GoogleTranslator(source='auto', target='ur')

persist_directory='ip+pdf'
# from langchain_community.embeddings import OllamaEmbeddings
# embedding = OllamaEmbeddings()
embedding = OpenAIEmbeddings()

vectordb=Chroma(persist_directory=persist_directory,
                embedding_function=embedding)
from langchain_community.llms import Ollama
## Load Ollama LAMA2 LLM model
# llm = OpenAI(temperature=0.3)
llm =Ollama(model="llama3.1")

## Design ChatPrompt Template
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""Given the following context and a question, generate an answer based on this context only.
You're a chatbot specializing in Indian law, particularly the Indian Penal Code (IPC). Your user seeks guidance on legal matters within the scope of the IPC.
Engage with them in a helpful and informative manner, providing accurate answers to their questions and clarifications regarding relevant legal concepts ,statutes.
Ensure your responses are clear, concise, and tailored to the specific queries posed.


In the answer try to provide as much text as possible from the source document context .
If the answer is not found in the context, kindly state "I don't know." Don't try to make up an answer.
<context>
{context}
</context>
Question: {input}
"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm,prompt)

retriever=vectordb.as_retriever()

from langchain.chains import create_retrieval_chain

In [116]:
retrieval_chain=create_retrieval_chain(retriever,document_chain)

In [117]:
response=retrieval_chain.invoke({"input":"What is a bail? What is anticipatory bail? How do I get a bail? How much I have to pay for a bail? Is that amount refundable? Can I take bail in advance if I know somebody is going to take a legal action against me (I did not do anything wrong)? How long a bail is valid? Does it have some expiry?"})

In [118]:
response

{'input': 'What is a bail? What is anticipatory bail? How do I get a bail? How much I have to pay for a bail? Is that amount refundable? Can I take bail in advance if I know somebody is going to take a legal action against me (I did not do anything wrong)? How long a bail is valid? Does it have some expiry?',
 'context': [Document(metadata={'page': 839, 'source': 'Indian Penal Code Book.pdf'}, page_content='without sureties, fails without suﬃcient cause (the burden of proving which shall lie\nupon him), to appear in Court in accordance with the terms of the bail or bond, shall\nbe punished with imprisonment of either description for a term which may extend to\none year, or with ﬁne, or with both.\nExplanation.—The punishment under this section is—\n(a)in addition to the punishment to which the offender would be liable on a\nconviction for the offence with which he has been charged; and\n(b)without prejudice to the power of the Court to order forfeiture of the bond].\nCOMMENT.—\nCr PC, 1973 (Amendment) Act 2005—clause 44.—This clause amends the IPC, 1860 as\nfollows, namely:—'),
  Document(metadata={'page': 197, 'source': 'Indian Penal Code Book.pdf'}, page_content='take place. The Court has, however, no power to refund ﬁne. If the time limit had been\nset by the Court for payment of ﬁne and the ﬁne amount is not paid within the time so\nﬁxed, then it goes without saying that the petitioner-accused has to either surrender\nbefore the Court or the prosecuting agency will be in a position to arrest him and\nproduce before Court for his detention in prison for undergoing the default\nsentence.216. In case of default in payment of ﬁne accused not obeying speciﬁc\ndirections as to making payment and postponing payment without surrendering into\nCourt. Accused is guilty of abuse of process of Court.217.'),
  Document(metadata={'source': 'ipctextcorpus.txt'}, page_content='first month has expired. If seventy -five rupees be paid or levied at the time of the expiration of the first month, or at any later \ntime while A continues in imprisonmen t, A will be immediately discharged. If fifty rupees of the fine be paid or levied before the \nexpiration of two months of the imprisonment. A will be discharged as soon as the two months are completed. If fifty rupees b e \npaid or levied at the  time of the expiration of those two months, or at any later time while A continues in imprisonment, A will be \nimmediately discharged.  \n70. Fine leviable within six years, o f during imprisonment. Death not to disc harge property \nfrom liability .—The fine, or any part thereof which remains unpaid, may be levied at any time within six \nyears after the passing of the sentence, and if, under the sentence, the offender be liable to imprisonment \nfor a longer period than six years, then at any time previous to the exp iration of that period; and the death'),
  Document(metadata={'source': 'ipctextcorpus.txt'}, page_content='Justice, with s imple imprisonment for a term which may extend to six months, or with fine which may \nextend to one  thousand rupees, or with both.  \nIllustrations  \n(a) A, being legal ly bound to appear before the 1[High Court] at Calcutta, in obedience to a subpoena issuing fr om that \nCourt, intentionally omits to appear. A has committed the o ffence defined in this section.  \n(b) A, being leg ally bound to appear before a 2[District Judge], as a witness, in obedienc e to a summons issued by that \n2[District Judge] intentionally omits  to appear. A has committed the offence defined in this section . \n3[174A .Non -appearance in response to a proclamation under section 82 of Act 2 of 1974 .—\nWhoever fails to appear at the specified place and the specified time as required by a proclamation \npublished under sub -section ( 1) of section 82 of the Code of Criminal Procedure, 1973 shall be punished')],
 'answer': 'Based on the provided context, here are the answers to your questions:\n\n**What is a bail?**\nA bail, as per Section 446 of the IPC, refers to a surety or bond that an accused person provides to ensure their appearance in court in accordance with the terms of the bail or bond. If they fail to appear without sufficient cause, they shall be punished.\n\n**What is anticipatory bail?**\nI don\'t know. The context provided does not mention "anticipatory bail."\n\n**How do I get a bail?**\nThe context does not provide information on how to obtain a bail. It only mentions the consequences of failing to appear in court without sufficient cause.\n\n**How much I have to pay for a bail?**\nI don\'t know. The context provided does not specify any amount related to bailing out or obtaining a bail.\n\n**Is that amount refundable?**\nIf the time limit had been set by the Court for payment of fine and the fine amount is not paid within the time so fixed, then the petitioner-accused has to either surrender before the Court or the prosecuting agency will be in a position to arrest him and produce before Court for his detention in prison for undergoing the default sentence. This implies that any fine related to bail is not refundable.\n\n**Can I take bail in advance if I know somebody is going to take a legal action against me (I did not do anything wrong)?**\nBased on the provided context, there\'s no information to suggest that taking anticipatory bail is possible. The IPC only discusses consequences of failing to appear in court without sufficient cause.\n\n**How long a bail is valid? Does it have some expiry?**\nUnfortunately, I don\'t know as this information is not available within the given context.'}

In [119]:
import pandas as pd
df=pd.read_csv("/Users/aasarmehdi/Downloads/qt1.csv")

In [120]:
df

,question,ground_truth,answer,contexts
0,Can someone build a house on land assigned for...,"In a residential colony, if a place is assigne...",NaN,NaN
1,Hi sir/Madam My husband always give me mentall...,When both of you and your sons are interested ...,NaN,NaN
2,"Sir, I worked in a RMC company as a third part...","Dear client, first contact the employer and as...",NaN,NaN
3,Someone hit my car from behind but I moved awa...,"It may be noted that currently, hit-and-run ca...",NaN,NaN
4,What is a bail? What is anticipatory bail? How...,Bail is a release of person who is accused of ...,NaN,NaN
5,My wife has filed a false divorce case against...,As far as your father and sisters are concerne...,NaN,NaN
6,How can file a Complaint in Consumer Court on ...,"This case do not attract Consumer Forum, & it'...",NaN,NaN
7,what can be done legally if someone is not ret...,suit for recovery can be filed.,NaN,NaN
8,can a sister have any claim on brothers salary...,In case the assets are joint and not divided s...,NaN,NaN
9,if Father is living and can a daughter demand ...,if it is an ancestral property then yes and if...,NaN,NaN
10,How we can file a suit for child custody?,You need to file a case in family court and if...,NaN,NaN
11,How to evict a tenant who did not gave my rent,by filing an eviction petition.,NaN,NaN
12,Can I cancel settlement deed for my minor chil...,you might have to seek court orders.,NaN,NaN
13,My friend insulted his lady relative by callin...,"Since the insult is on provocation, an offence...",NaN,NaN
14,Is it necessary that a private limited company...,NO. .... Private company land can be sold by a...,NaN,NaN
15,Is Identity Card Number of Next of Kin is mand...,"All banks have different rules, but in case of...",NaN,NaN
16,Sir I have purchased house from builders. Some...,A builder cannot ask for any payment post-regi...,NaN,NaN
17,Relative found a 2 floored rented shop through...,It appears that you made a bad investment by d...,NaN,NaN

In [78]:
df["question"][5:]

5     We both are having difference. Can I move abro...
6     In India my mother want to gift me property bu...
7     Something has happened with me today, i was dr...
8     My wife has filed a false divorce case against...
9     How can file a Complaint in Consumer Court on ...
10    what can be done legally if someone is not ret...
11    can a sister have any claim on brothers salary...
12    if Father is living and can a daughter demand ...
13    Can a girlfriend of a man get custody rights t...
14            How we can file a suit for child custody?
15       How to evict a tenant who did not gave my rent
16    Can I cancel settlement deed for my minor chil...
17    My friend insulted his lady relative by callin...
18    Is it necessary that a private limited company...
19     time limitation to file case for probate of will
20    Is Identity Card Number of Next of Kin is mand...
21    Salam sir due to my mistake I had paid late in...
22    Sir I have purchased house from builders. Some...
23    Relative found a 2 floored rented shop through...
Name: question, dtype: object

In [121]:
a=df["question"]

In [122]:
df["question"]

0     Can someone build a house on land assigned for...
1     Hi sir/Madam My husband always give me mentall...
2     Sir, I worked in a RMC company as a third part...
3     Someone hit my car from behind but I moved awa...
4     What is a bail? What is anticipatory bail? How...
5     My wife has filed a false divorce case against...
6     How can file a Complaint in Consumer Court on ...
7     what can be done legally if someone is not ret...
8     can a sister have any claim on brothers salary...
9     if Father is living and can a daughter demand ...
10            How we can file a suit for child custody?
11       How to evict a tenant who did not gave my rent
12    Can I cancel settlement deed for my minor chil...
13    My friend insulted his lady relative by callin...
14    Is it necessary that a private limited company...
15    Is Identity Card Number of Next of Kin is mand...
16    Sir I have purchased house from builders. Some...
17    Relative found a 2 floored rented shop through...
Name: question, dtype: object

In [123]:
j=0
for i in a:
    response=retrieval_chain.invoke({"input":i})
    df['answer'][j]=response['answer']
    df['contexts'][j]=response['context']
    j+=1

/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_11213/4284119625.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_11213/4284119625.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_11213/4284119625.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Based on the provided context, I must state that the specific scenario you're asking about (building a house on land assigned for shops) is not explicitly discussed. However, there are discussions under section 442 of the IPC regarding buildings used as human dwellings or places for the custody of property.

From the discussion under "Building" in section 442, infra, it's mentioned that:

"...a building which is used as a human dwelling or as a place for the custody of property... would come within the meaning of building if it is used as a human dwelling or place for the custody of property."680

However, this does not directly answer your question about building on land assigned for shops. The closest related information from section 442 mentions police stations and buildings used for various purposes but does not explicitly address the scenario you've asked.

Therefore, without explicit context or law that addresses such a specific scenario directly, I must say "I don't know" regarding the legality of building a house on land assigned for shops in your colony. The situation might fall under specific local regulations or bylaws which are not mentioned here.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_11213/4284119625.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['contexts'][j]=response['context']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_11213/4284119625.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['contexts'][j]=response['context']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_11213/4284119625.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[Document(metadata={'page': 1577, 'source': 'Indian Penal Code Book.pdf'}, page_content="the Legislature in framing section 436, IPC, 1860, was to give protection to those\nbuildings which are used as human dwelling or as places where properties are stored\nfor custody.\nSee also discussions under head 'Building' under section 442, infra."), Document(metadata={'page': 1591, 'source': 'Indian Penal Code Book.pdf'}, page_content='673. Appukuttan v State, 2010 Cr LJ. 3186 .\n674. Vide Explanation.\n675. Dinesh Thakur, 1970 Cr LJ 1199 .\n676. Md. Sahabuddin v Sayed Monowar Hussain, 1999 Cr LJ. 349 (Gau).\n677. Moir v Williams, (1892) 1 QB 264 , 270.\n678. Palani Goundan, (1896) 1 Weir 523.\n679. Rajoo v State, 1977 Cr LJ 837 (Raj).\n680. State of Karnataka v Richard, 2008 Cr LJ 2200 (Kar).thatched roof, doors and shutters would come within the meaning of building if it is\nused as a human dwelling or place for the custody of property.679..\n[s 442.1] Police Station.—\nThe criminal trespass in question need not be only in respect of a building used as a\nhuman dwelling, but it also covers in building used as a place for custody of property\nand as the police station is a place where there will also be custody of property, it will\nalso come under the deﬁnition of "Building" in section 442 IPC, 1860.680.'), Document(metadata={'page': 645, 'source': 'Indian Penal Code Book.pdf'}, page_content='Jaya Publications. While reversing the conviction passed by the High Court, the\nSupreme Court held that the offence under section 169 IPC, 1860 is incomplete without\nthe assistance of some other enactment which imposes the legal prohibition required.\nTherefore, in order to come within the clutches of section 169 IPC, 1860, there should\nbe a law which prohibits a public servant from purchasing certain property and if he\ndoes it, it becomes an offence under section 169 IPC, 1860. Section 481 of the Criminal\nProcedure Code, section 189 of the Railways Act, 1989 and section 19 of the Cattle\nTrespass Act, 1871 and instances of that nature in several enactments are available in\nwhich persons mentioned therein shall not directly or indirectly purchase any property\nat a sale under those Acts. Similarly section 136 of the Transfer of Property Act, 1882\nprovides that no Judge, legal practitioner, or oﬃcer connected with any Court of Justice'), Document(metadata={'page': 612, 'source': 'Indian Penal Code Book.pdf'}, page_content='212. M&M 128.\n213. Kazi Zeamuddin Ahmed, (1901) 28 Cal 504 ; Payag Singh, (1890) 12 All 550 .\n214. Rule 252, Bengal Police Regulations, vol I 1943, p 108.\n215. MK Ibrahim, 1979 Cr LJ 175 (Kant); Indu Bhushan v State, 1995 Cr LJ 1180 (Cal).COMMENT—\nLiability of owner or occupier of land used for unlawful assembly.— Many duties of the\npolice are by law imposed on land-holders. The present section proceeds apparently\nupon a presumption that, in addition to any such duty, the owner or occupier of land is\ncognizant in a peculiar way of the designs of those who assemble on his land, and is\nable not only to give the police notice, but also to prevent and to disperse and suppress\nthe assembly.212.\nSection 45 of the Cr PC, 1973, casts upon the owners and occupiers of land the duty of\npreventing a riot on their lands.\nKnowledge, on the part of the owner or occupier of the land, of the acts or intentions of\nthe agent, is not an essential element of an offence under this section, and he may be')]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['contexts'][j]=response['context']

In [124]:
df

,question,ground_truth,answer,contexts
0,Can someone build a house on land assigned for...,"In a residential colony, if a place is assigne...","Based on the provided context, I must state th...",[page_content='the Legislature in framing sect...
1,Hi sir/Madam My husband always give me mentall...,When both of you and your sons are interested ...,"I can't provide legal advice, but I can offer ...",[page_content='were persistently torturing her...
2,"Sir, I worked in a RMC company as a third part...","Dear client, first contact the employer and as...",I don't see any relevant information regarding...,[page_content='Where a conviction under sectio...
3,Someone hit my car from behind but I moved awa...,"It may be noted that currently, hit-and-run ca...","Based on the context provided, it seems that y...",[page_content='truck against the cyclist and t...
4,What is a bail? What is anticipatory bail? How...,Bail is a release of person who is accused of ...,Given the context of the Indian Penal Code (IP...,"[page_content='without sureties, fails without..."
5,My wife has filed a false divorce case against...,As far as your father and sisters are concerne...,I cannot provide legal advice. If you are expe...,[page_content='an offence under this section.3...
6,How can file a Complaint in Consumer Court on ...,"This case do not attract Consumer Forum, & it'...",I don't know.,[page_content='said ﬁxed deposit adjusted a pa...
7,what can be done legally if someone is not ret...,suit for recovery can be filed.,"Based on the provided context, I'd like to add...","[page_content='take place. The Court has, howe..."
8,can a sister have any claim on brothers salary...,In case the assets are joint and not divided s...,I don't know.\n\nThe provided context does not...,[page_content='wherefrom the ingredients of an...
9,if Father is living and can a daughter demand ...,if it is an ancestral property then yes and if...,I don't know.\n\nThe provided context discusse...,[page_content='list of ornaments and other hou...
10,How we can file a suit for child custody?,You need to file a case in family court and if...,I don't know. The provided context appears to ...,"[page_content='the other parent, who held such..."
11,How to evict a tenant who did not gave my rent,by filing an eviction petition.,I'm not able to provide legal advice specific ...,[page_content='determination of tenancy by not...
12,Can I cancel settlement deed for my minor chil...,you might have to seek court orders.,"Based on the provided context, I must inform y...",[page_content='consent of guardian.\nNothing w...
13,My friend insulted his lady relative by callin...,"Since the insult is on provocation, an offence...",I cannot provide legal advice. If you are conc...,[page_content='words must amount to something ...
14,Is it necessary that a private limited company...,NO. .... Private company land can be sold by a...,"Based on the context provided, I don't see any...",[page_content='wherefrom the ingredients of an...
15,Is Identity Card Number of Next of Kin is mand...,"All banks have different rules, but in case of...",I don't know. The context provided seems to be...,[page_content='villagers taking injured in bul...
16,Sir I have purchased house from builders. Some...,A builder cannot ask for any payment post-regi...,"Based on the context provided, it seems like y...",[page_content='untenable.329. The complaint do...
17,Relative found a 2 floored rented shop through...,It appears that you made a bad investment by d...,I can help you understand your situation bette...,[page_content='warehouse room. A dishonestly s...

In [125]:
df.to_csv("final_ollama3.1_only_llm.csv")

# deleting db

In [ ]:
!zip -r db.zip ./db

In [ ]:
vectordb.delete_collection()
vectordb.persist()

# delete the directory
!rm -rf db/

# starting again loading db

In [ ]:
!unzip db.zip